alphagov/gsp

modules/flux-release/data/flux.yaml, modules/flux-release/data/helm-release.yaml, modules/flux-release/data/namespace.yaml, modules/flux-release/data/values-secret.yaml, modules/flux-release/main.tf, modules/flux-release/variables.tf
move the flux release module out of gsp-teams repo and into this repo as
we want gsp-teams to be a pure consumer of the modules
=> add flux-release module

bootstrapper/bootstrap.sh, modules/gsp-cluster/harbor.tf, modules/gsp-cluster/main.tf, modules/gsp-cluster/outputs.tf, modules/k8s-cluster/iam.tf
Harbor is now part of the `ci-system` and it requires some automatically generated credentials along with a s3 bucket for storing images.
These secrets will be output by terraform and passed onto the `ci-system-main`. We need to make sure concourse knows about that namespace.
- ?
⚠️ Remove the TMP commit
=> Preparation for Harbor

modules/bootkube-ignition/data/manifests/aws-iam-authenticator-cfg.yaml, modules/bootkube-ignition/manifests.tf, modules/bootkube-ignition/variables.tf, modules/group-role-bindings/data/role-binding.yaml, modules/group-role-bindings/data/role.yaml, modules/group-role-bindings/main.tf, modules/group-role-bindings/variables.tf, modules/gsp-cluster/iam.tf, modules/gsp-cluster/main.tf, modules/gsp-cluster/variables.tf, modules/k8s-cluster/variables.tf
Reference: https://trello.com/c/nCrJOJZj/126-per-deployment-iam-roles-for-limited-kubectl-access
=> Create Dev role

modules/lambda_splunk_forwarder/lambda.tf
https://github.com/hashicorp/terraform/issues/6513
File references are processed before depends_on dependancies. This
appears to be causing an error where terraform can not apply as
it can not find the lambda zip file it expects to be there.
I have followed the approach suggested by
https://github.com/hashicorp/terraform/issues/6513#issuecomment-271528697.
It works fine locally.
=> Use archive data types and local files to get around terraform bug

bootstrapper/bootstrap.sh, bootstrapper/main.tf, modules/etcd-cluster/variables.tf, modules/gsp-cluster/main.tf, modules/k8s-bootstrap/variables.tf, modules/k8s-cluster/variables.tf
Some miscellaneous tidying up.
=> Remove unused variables & bootstrapper bugfix

modules/gsp-cluster/outputs.tf
https://trello.com/c/Ls4FR1R1/207-provision-the-aws-hsm
=> Output private subnet ids to place AWS HSM into

modules/gsp-cluster/secrets.tf, modules/gsp-cluster/variables.tf
This causes issues in our sandbox clusters. We are planning on playing
story to separate the essentials into it's own terraform state, but
that's to come.
https://github.com/hashicorp/terraform/issues/3116
- Code review should suffice
=> Revert prevent destroy

modules/gsp-cluster/outputs.tf
Left over from the "persistent" refactor.
=> Remove lingering attribute.

modules/gsp-cluster/data/aws-ssm-agent-daemonset.yaml, modules/gsp-cluster/main.tf, modules/k8s-cluster/iam.tf
Adds the SSM agent as a daemonset to the cluster.
Related: https://github.com/alphagov/gsp-docker-images/pull/13
=> Add SSM agent

modules/k8s-cluster/main.tf
=> Add control plane logging.

modules/gsp-cluster/main.tf, modules/gsp-cluster/variables.tf, modules/k8s-cluster/main.tf, modules/k8s-cluster/variables.tf
Expose a variable for specifying the EKS version.
=> Specify the EKS version.

pipelines/README.md, pipelines/deployer/deployer.yaml
...because we forgot to do it before merging.
=> Fix the pipeline and update the readme.

docs/architecture/gsp-architecture.md
=> correct typo in link

docs/gds-supported-platform/getting-started-gsp.md
Coping in @jonathanglassman's Getting Started with GSP PR to this repo so it can be signed / approved correctly.
Replaces #79
=> Getting Started with GSP

modules/gsp-cluster/data/values.yaml
=> Correctly set `runningOnAws` configuration

README.md, charts/gsp-cluster/templates/02-gsp-system/concourse-web-virtual-service.yaml, charts/gsp-cluster/templates/02-gsp-system/flux.yaml, charts/gsp-cluster/templates/02-gsp-system/harbor-virtual-service.yaml, charts/gsp-cluster/values.yaml, modules/gsp-cluster/data/values.yaml, pipelines/examples/users/sam.crang.yaml, scripts/gsp-local.sh, scripts/local-values.yaml
This migrates us to using Istio `VirtualService`s rather than `Ingress`es. It also does some work towards making the local development experience closer to The Dream™ (aka everything Just Works®).
=> Local ingress

modules/hsm/main.tf, pipelines/deployer/deployer.tf
Provision a CloudHSM cluster and expose its IP address(es).
=> Resurrect the HSM.

modules/hsm/main.tf, pipelines/deployer/deployer.tf
I suspect this won't work due to terraform's `count` weirdness...but I wanted to try it first before hardcoding stuff all over the place.
=> Attempt to fix hsm provisioning.

pipelines/deployer/deployer.yaml
assign to var before eval else an error will not be caught by the bash
"-e" and execution will continue onwards
=> assume role before eval env

docs/gds-supported-platform/setting-up-hsm.md, hack/Vagrantfile
- Using a vagrant image to sign the HSM's CSR.
- Updates to the documentation.
=> Updates & streamlining HSM initialisation

scripts/gsp-local.sh, scripts/hack/create-gsp-main-namespace.yaml, scripts/hack/expose-grafana.yaml, scripts/hack/expose-prometheus.yaml, scripts/hack/make-coredns-resolve-local-to-istio-gateway.yaml, scripts/local-values.yaml
I'd like to get this merged because it means that the local GSP (which we want to user test on Wednesday) will actually work.
I've had to disable/tweak a bunch of things that seem to be broken locally but we should look at these later.
=> Fix local GSP ready for user testing

charts/gsp-cluster/templates/02-gsp-system/pipeline-operator-role.yaml, charts/gsp-cluster/templates/02-gsp-system/pipeline-operator.yaml
😇 sorry...
* fixes rbac again
* sets team name prefix to match reality
=> fixes rbac resource names which should be plural

charts/gsp-cluster/templates/03-namespaces/namespace.yaml
=> strip the hyphen from the prefix too

modules/gsp-cluster/vpc-flow-logs.tf
Fixing a typo in defining the iam_role_arn for the aws_flow_log
=> Fix iam flow log

docs/gds-supported-platform/accessing-concourse.md
Service name changed and namespace changed.
=> fix the port forward command for concourse

pipelines/deployer/deployer.yaml
we want the "main" team to have all the same nice secrets and config as the other team namespaces.
=> remove gsp- filter and include -main ns in list

pipelines/deployer/deployer.yaml
They are flakey. We should investigate this at a later date.
=> Disable conformance tests

modules/k8s-cluster/main.tf
Change has not yet been tested.
Pair: @poveyd, @smford
=> Change to add --event-qps flag

docs/gds-supported-platform/getting-started-gsp-local.md
Otherwise this makes no sense. Per Issy.
=> Fix order of brew bundle/git clone steps

charts/gsp-cluster/templates/03-namespaces/namespace.yaml, hack/lint-terraform-values-output.sh
chart failed to render for namespaces with scope=null ... so default it to "namespace"
=> Fix namespace scope

charts/gsp-cluster/templates/03-namespaces/namespace.yaml
=> fix typo in config pipeline

charts/gsp-cluster/values.yaml
Fixes issue with incorrect CertDir ... pipeline-operator  code has moved into gsp tree
=> bump pipeline-op to fix CertDir issue

pipelines/deployer/deployer.yaml
Let's have the test jobs split out so we can see them and re-trigger them
=> split the test jobs out so we can see them

pipelines/deployer/deployer.yaml
... I always forget the "groups" 😇
=> fixes incorrect deployer pipeline groups

docs/gds-supported-platform/getting-started-gsp-local.md
Content approved by GSP SMEs, Tech Writing 2i, and Comms
=> Updated GSP local env docs

README.md
=> whitespace

modules/gsp-cluster/concourse.tf, modules/gsp-cluster/harbor.tf, modules/gsp-cluster/kiam-system.tf, modules/gsp-cluster/monitoring-system.tf, modules/k8s-cluster/data/nodegroup.yaml, modules/k8s-cluster/iam.tf
=> AWS Service Operator Role

docs/gds-supported-platform/getting-started-gsp-local.md, scripts/gsp-local.sh
- Move cloning the repo to step 1 in the instructions
- Add a check to disable the default minikube dashboard
=> BAU: Improve GSP local script

pipelines/deployer/deployer.yaml, pipelines/release/release.yaml
Attempt to fix the github-resource tag prefix so it picks the correct tags.
=> Make the tag prefix more strict.

.gitignore, charts/gsp-cluster/templates/02-gsp-system/https-egress-safelist.yaml, charts/gsp-cluster/values.yaml, hack/lint-terraform-values-output.sh, modules/gsp-cluster/data/values.yaml
Allow provided FQDNs out via the istio egressgateway.
=> Add HTTPS egress safelist

docs/gds-supported-platform/setting-up-hsm.md
Updating to fix typo in path to cloud hsm user password held within ssm.
Solo: @smford
=> Update documentation on extracting hsm user password

charts/gsp-cluster/templates/02-gsp-system/https-egress-safelist.yaml
Merge with https://github.com/alphagov/verify-proxy-node/pull/265
=> Migrate https egress safelist to mTLS.

docs/gds-supported-platform/setting-up-hsm.md
Making a little clearer that hijacked containers from central concourse is required.
Solo: @smford
=> Updating the documentation to clarify how to access SSM

docs/architecture/adr/README.md
this is a difficult word but if i learnt one thing from working on
Registers it was how to spell it
=> fix spelling of "supersede"

docs/README.md, docs/gds-supported-platform/making-things-private-in-harbor.md
Also:
- Add link to Harbor documentation in README.md
=> Fix some small mistakes in Harbor documentation

modules/gsp-cluster/data/values.yaml
Will hopefully make one of the alerts less noisy.
=> Double the volume size of harbor's database.

pipelines/deployer/deployer.yaml
=> Remove cleanup from deployment pipeline.

pipelines/deployer/deployer.tf, pipelines/deployer/main.tf
=> Also run terraform 0.12upgrade in the deployer pipeline directory

modules/gsp-cluster/nlb.tf
=> Uncomment some things that were accidentally left commented

modules/gsp-cluster/main.tf, modules/gsp-cluster/variables.tf, modules/k8s-cluster/main.tf, modules/k8s-cluster/variables.tf, pipelines/deployer/deployer.tf, pipelines/deployer/deployer.yaml
This reverts commit 307f8a3cf8066c24dde4c16ed8fef57a7053fc70.
Error: Variables not allowed
Variables may not be used here.
https://github.com/hashicorp/terraform/issues/3116
=> Revert "Unbreak the cluster destroy job"

pipelines/release/release.yaml
=> Fix repo for terraform resource

components/concourse-harbor-resource/assets/out
we are debugging a harbor issue and want to be sure we can see the
harbor endpoint
=> log harbor api endpoint

docs/architecture/adr/README.md
=> Register ADR041 on list of ADRs

modules/gsp-cluster/service-operator.tf
This reverts commit aa97306982599c4272fd2bcb39a2e312400c4e68.
Decided to go ahead with this and deal with the existing database.
=> Revert "Partially revert #706 to get Terraform apply working"

pipelines/deployer/deployer.yaml
=> Scale cluster autoscaler down to 0 replicas during terraform apply

pipelines/deployer/deployer.yaml
otherwise we haven't actually assumed the role
=> actually eval the AWS_CREDS

charts/gsp-cluster/templates/02-gsp-system/harbor-virtual-service.yaml
This reverts commit 0d96cf515d143210ef612758fad6e51462110a8a.
resolves harbor issues
=> Revert "Remove public access to the Habor API/Portal"

pipelines/deployer/deployer.yaml
This reverts commit edc8f2beb28db328f8dca8556165afacb056713f.
=> Revert "Cleanup old client IP safelisting stuff"

.gitignore, charts/gsp-cluster/templates/02-gsp-system/service-operator/crd/database.govsvc.uk_postgres.yaml, charts/gsp-cluster/templates/02-gsp-system/service-operator/crd/storage.govsvc.uk_s3buckets.yaml, components/service-operator/apis/database/v1beta1/postgres_types.go, components/service-operator/apis/database/v1beta1/postgres_types_test.go, components/service-operator/config/rbac/role-not-patch.yaml, components/service-operator/go.sum
It was agreed this would be hardcoded for now.
* Commit by commit
* Ignore whitespace for the go changes
=> Keep RDS automated backups for 7 days.

pipelines/release/release.yaml
add missing s3 region :roll_eyes:
=> fix s3 public region for lifecycle zip

pipelines/release/release.yaml
concourse s3 resource doesn't support iam profiles correctly, the paas
fork implements this, so use theirs.
=> use the paas team's s3-resource

docs/gds-supported-platform/helm-chart-best-practices.md
some notes from daniel's auditing some of the helm charts we have seen,
maybe we will neaten and expand this into something more concrete... it's just a start, but best to get it into the docs bit before we lose it
=> start making some chart writing tips/notes

modules/k8s-cluster/data/nodegroup-v2.yaml
Just while we're working on getting rid of them.
=> Temporarily re-allow existing instance types

modules/gsp-cluster/data/values.yaml
Don't forget:
https://github.com/alphagov/gsp/blob/master/docs/gds-supported-platform/resizing-persistent-volumes.md
=> Increase the size of the harbor database persistent volume.

modules/gsp-cluster/cluster-autoscaler.tf, modules/gsp-cluster/kiam-system.tf, modules/gsp-cluster/nlb.tf, modules/gsp-cluster/service-operator.tf, modules/k8s-cluster/aws-node-lifecycle-hook.tf, modules/k8s-cluster/main.tf, modules/k8s-cluster/security.tf, modules/lambda_splunk_forwarder/iam.tf, modules/lambda_splunk_forwarder/lambda.tf
The result of:
`terraform fmt --recursive`
=> Terraform fmt.

charts/gsp-cluster/values.yaml, pipelines/deployer/deployer.yaml
Clair is causing trouble and we don't currently use it.
=> Disable clair.

charts/gsp-cluster/policies/README.md, charts/gsp-cluster/policies/restrict-special-nodes/src.rego, charts/gsp-cluster/policies/restrict-special-nodes/src_test.rego
Don't require it to be set to Exists to block
See https://kubernetes.io/docs/concepts/configuration/taint-and-toleration/
=> Also block toleration operator Equal for special nodes

charts/gsp-cluster/templates/02-gsp-system/harbor-databases.yaml, modules/gsp-cluster/data/values.yaml, modules/gsp-cluster/grafana.tf, modules/gsp-cluster/harbor.tf, modules/gsp-cluster/service-operator.tf, modules/gsp-cluster/values.tf, modules/gsp-cluster/variables.tf, modules/gsp-network/outputs.tf, modules/gsp-subnet/outputs.tf, pipelines/deployer/deployer.tf, pipelines/deployer/deployer.yaml
:exclamation: :warning: Data Loss!
If we don't migrate the data (somehow) we lose it all.
=> Use RDS for harbor's databases.

docs/gds-supported-platform/bootstrapping-clusters.md
Correct a couple of minor items found during testing this document.
=> edit path to cluster configs and add pwd for command

docs/gds-supported-platform/bootstrapping-clusters.md
**Why**
These vars were not defined and creating an error when the fly command was executed.
**What**
Add guidance to set values according to the example in PR #268.
=> add undefined vars to make our lives simpler

modules/gsp-cluster/data/values.yaml, modules/gsp-cluster/grafana.tf
Instead of the metadata service and KIAM.
=> Switch Grafana to using IAM roles for EKS Service Accounts

.dependabot/config.yml
we should be keeping up to date with dependencies, try out dependabot on
dockerfile for service-operator.
=> enable dependabot for service-operator docker img

charts/gsp-cluster/templates/02-gsp-system/service-operator/deployment.yaml, charts/gsp-cluster/templates/02-gsp-system/service-operator/service-account.yaml, charts/gsp-cluster/values.yaml, components/service-operator/go.mod, components/service-operator/go.sum, modules/gsp-cluster/data/values.yaml, modules/gsp-cluster/service-operator.tf, modules/gsp-cluster/values.tf
Only the Service Operator itself, not any tenant stuff.
=> Switch Service Operator to using IAM roles for EKS Service Accounts

components/concourse-task-toolbox/Dockerfile
Upgrading kapp to a version that is less loquacious and supports configmap
garbage collection.
=> Upgrade kapp

charts/gsp-cluster/templates/04-main-team-pipelines/cd-smoke-test-pipeline.yaml
As per https://github.com/k14s/kapp/blob/master/docs/state-namespace.md#app-changes
=> Garbage collect old canary kapp state changes

charts/gsp-cluster/templates/03-namespaces/external-dns.yaml
=> Revert "Update external-dns from 0.5.15 to 0.5.18"

modules/gsp-cluster/values.tf
Follows up https://github.com/alphagov/gsp/pull/874
=> Clean up another old KIAM reference to the service operator

components/concourse-operator/pkg/controller/pipeline/pipeline_controller_test.go
forgot to update the test since changing default of check-creds
=> fix: update check-creds test

pipelines/deployer/deployer.yaml, pipelines/release/release.yaml
Reverts https://github.com/alphagov/gsp/pull/937
=> Revert set_pipeline

charts/gsp-cluster/templates/03-namespaces/namespace.yaml, charts/gsp-cluster/templates/04-main-team-pipelines/cd-smoke-test-pipeline.yaml
Introduced in #545, reduces a bit of noise from our tasks
=> use the setup-kube-deployer script

charts/gsp-cluster/templates/03-namespaces/namespace.yaml, components/canary/chart/templates/deployment.yaml
fixing: https://github.com/alphagov/gsp/pull/984
=> fixing forward for #984

charts/gsp-cluster/templates/03-namespaces/namespace.yaml
=> fixing forward for #986

modules/k8s-cluster/data/nodegroup.yaml
PR back from the dead to roll nodes by midifying the nodegroup
=> Remove bad instance types

charts/gsp-cluster/templates/03-namespaces/namespace.yaml, pipelines/deployer/deployer.yaml
This reverts commit 9c7e75b226ddff8d67d85779b64273b38d116b12.
Temporary code will have run. Need to ensure previous release is promoted.
=> Revert "Follow-up #966: Delete old Harbor resources"

charts/gsp-cluster/charts/gsp-monitoring/values.yaml
With KIAM gone this should work fine now?
=> Put Grafana back where we found it

modules/k8s-cluster/main.tf, pipelines/deployer/deployer.yaml
=> remove special chars from timestamp

modules/gsp-cluster/main.tf, modules/gsp-cluster/variables.tf, modules/k8s-cluster/main.tf, modules/k8s-cluster/variables.tf, pipelines/deployer/deployer.tf, pipelines/deployer/deployer.yaml
reverts #1010 as it fails to bring up healthy nodes ... I suspect the args are weirdly escaped or invalid
=> Revert messing with labels

components/service-operator/apis/database/v1beta1/redis_types.go, components/service-operator/controllers/redis_cloudformation.go
I last tried to build/test it before I merged packages.
Follow-up to #1022
=> svcop: Fix build now that redis support is in the database package

components/service-operator/apis/database/v1beta1/redis_types_test.go
Follow-up #1022
This should never have passed.
=> svcop: Fix redis types test

components/concourse-operator/pkg/controller/team/team_controller.go
concourse's team model currently requires at least one "admin" team
(usually called "main") because authenication is tied to a team.
the concourse-operator requires that the "main" team exists as the operator
credentials are for the "main" team.
we have had issues where the deletion of the main team causes other
operator faliures and Team resources getting stuck in deleteing states.
this workaround is a bit lazy (only logs team destroy errors), but:
1. in the future there are plans to decouple concourse auth from teams,
which would make this problem much easier to solve / moot
2. teams are rarely destroyed (except with on-demand clusters) so it's
not worth the engineering effort right now to resolve it nicely
=> ignore errors deleteing concourse Team resources

pipelines/deployer/deployer.yaml
* Attempt the drain step multiple times
* Add some more logging to drain script
We saw timeouts/flakes that worked on second try, no harm in trying twice to get a more reliable destroy completion.
Extra logging help spot where it has died as some parts of script have ambiguous logging.
=> attempt drain multiple times

components/service-operator/internal/aws/cloudformation/client.go
Instead of disregarding errors and leaving empty info.
I believe this to be the cause of yesterday's issues.
=> svcop: Try to catch errors when setting info from outputs

modules/gsp-network/network.tf
It seems this should be enough to get logs shipped via the endpoint rather than
the NAT Gateway. This changes DNS resolutions within the cluster to have
this:
(after apt update and apt install dnsutils)
root@gsp-fluentd-cloudwatch-8nzph:/home/fluent# dig +short logs.eu-west-2.amazonaws.com
10.101.24.69
10.101.133.238
10.101.93.108
Whereas externally you get a non-RFC1918 IP like 52.94.48.143.
And the cluster seems to trust the cert served etc. Logs appear to be getting
shipped in my cluster.
TODO: Do we want to hide this behind a flag to enable it on a per-cluster basis?
=> Create cloudwatch logs VPC endpoint

pipelines/deployer/deployer.yaml
This was after a conversation with DCS and aligns with when the service
is quieter.
=> Do the node rolling at 1000

pipelines/deployer/deployer.yaml
=> Use the renamed resourced

docs/gds-supported-platform/gsp-service-operator.md
=> Add pretty colours to documentation

charts/gsp-cluster/charts/gsp-monitoring/values.yaml
To hopefully resolve issues on the DCS dashboard.
See #1009.
=> Raise Prometheus maxSamples by 2.5x

components/concourse-task-toolbox/bin/findCVEs.py
Got rid of these from sandbox-proxy-node-dev.
=> Remove a lurking Harbor reference

README.md
I think the git resource is too smart for its own good and is ignoring our empty commit.
=> Add a newline to the README

components/concourse-task-toolbox/bin/findCVEs.py
=> check-vulns: Allow script to proceed past broken images

components/concourse-task-toolbox/bin/findCVEs.py
Following https://github.com/alphagov/gsp/pull/1129
=> check-vulnerabilities: Update whitelist entries for Prometheus update

pipelines/deployer/deployer.defaults.yaml
EKS 1.14 -> 1.15 control plane upgrade
=> EKS 1.15 upgrade

README.md
=> bump badge 1.15

pipelines/deployer/deployer.defaults.yaml
An experiment to see if this fixes strange behaviour with the set_pipeline
step.
=> Try removing the default config-path.

pipelines/deployer/deployer.yaml
Perhaps the "override" behaviour isn't.
=> Reverse ordering of variable files in set_pipeline

.secrets.baseline
Following the instructions here:
https://github.com/alphagov/gds-pre-commit/blob/master/usage.md#check-in-your-secretsbaseline-file
=> check in .secrets.baseline

components/concourse-github-resource/assets/in
Seems to change sorting @jkunle vs. @j-maynard
=> concourse-github-resource: Use the default sort options for seemingly best comm behaviour

pipelines/deployer/deployer.yaml
=> Revert "Delete immutable objects from previous prometheus installation"

components/concourse-task-toolbox/bin/findCVEs.py
Based on https://cd.gds-reliability.engineering/teams/gsp/pipelines/verify-deployer/jobs/check-vulnerabilities/builds/103
=> Update vulnerabilities safelist following prometheus upgrade

charts/gsp-cluster/dashboards/concourse.json
Prefer proportion used over proportion free.
=> Improve node memory metric in concourse dashboard.

modules/k8s-cluster/data/nodegroup.yaml
By adding a comment about changing the nodegroup stack.
=> Replace cluster management nodes

components/concourse-task-toolbox/Dockerfile
gpg command has gone walkabouts, add it back
=> task-toolbox: add back gnugpg

docs/gds-supported-platform/updating-EKS.md, hack/lint-terraform-values-output.sh, pipelines/deployer/deployer.defaults.yaml
Don't do this until after #1170.
=> Roll out EKS 1.16 upgrade itself

components/concourse-task-toolbox/bin/findCVEs.py
It changed in 566cd0e6b3e66f2ec8ab98b30ed4c80dce1c51c6
=> check-vulnerabilities: Update version of Typha in use

modules/gsp-cluster/data/values.yaml
Based on https://github.com/alphagov/prometheus-aws-configuration-beta/pull/422
=> Use new alertmanager names

charts/gsp-cluster/charts/gsp-monitoring/dashboards/pod-availability.json, charts/gsp-cluster/charts/gsp-monitoring/templates/pod-availability-dashboard.yaml
Will hopefully help with diagnosing future node-rolling issues.
=> Add a pod-availability grafana dashboard

charts/gsp-cluster/charts/gsp-monitoring/dashboards/pod-availability.json
Include some panels relating to unschedulable pods.
=> Update pod-availability dashboard

components/aws-ssm-agent/README, components/concourse-operator/README.md
In order to have their latest commits be in a PR approved by people who are
still allowed to give such approvals.
=> Touch the concourse-operator and aws-ssm-agent directories

components/canary/chart/templates/deployment.yaml
=> Pull canary with DockerHub credentials

README.md
It was out of date and also we need to trigger the release pipeline for #1206
=> Update Kubernetes version in README

components/aws-node-lifecycle-hook/main.go, components/aws-ssm-agent/README, components/concourse-operator/README.md, components/concourse-task-toolbox/README.md, components/concourse-terraform-resource/README.md, components/service-operator/README.md
So Concourse will be happier.
This is just whitespace and full stops.
=> Touch a bunch of files where the last committers/approvers have left
