alphagov/gsp

modules/k8s-bootstrap/main.tf

This will allow the bootstrapper node to be easily identified by a
calling script that we may want to write to automate the up-down nature
of the bootstrapper.

Add bootstrapper label to boostrap node.

---

modules/etcd-cluster/iam.tf
modules/etcd-cluster/ignition.tf
modules/etcd-cluster/variables.tf
modules/gsp-cluster/iam.tf
modules/gsp-cluster/main.tf
modules/gsp-cluster/network.tf
modules/k8s-bootstrap/ignition.tf
modules/k8s-cluster/iam.tf
modules/k8s-cluster/ignition.tf
modules/k8s-cluster/variables.tf

Previously this was done using a vpc endpoint with an s3 bucket policy
that allowed access to anything coming from that vpc. Of course, every
vpc we spun up broke the bucket policy for the others. So, we have
reversed the policy so it is controlled from the things doing the accessing
(ec2 instance profiles) rather than being controlled from the thing being
accessed (s3 bucket objects).

Control access to the s3 user data via instance profiles.

---

modules/k8s-bootstrap/main.tf

To prevent the actual control plane from being scheduled onto the
bootstrapper.

Mark bootstrapper with different taints.

---

modules/etcd-cluster/ignition.tf
modules/gsp-cluster/outputs.tf
modules/k8s-bootstrap/ignition.tf
modules/k8s-cluster/ignition.tf

A race condition existed whereby an instance could start and try and load
the user data from the s3 bucket but the terraform hadn't uploaded the
object yet. This should ensure that race condition doesn't happen.

Ensure the s3 bucket object has been uploaded before instance creation.

---

modules/canary-release/main.tf
modules/canary-release/variables.tf

we want gsp-teams to be a consumer of the terraform modules only so this
moves the last remaining module for the canary into this repo

move canary module from gsp-teams

---

modules/gsp-cluster/main.tf
modules/k8s-cluster/security.tf
modules/k8s-cluster/variables.tf

We don't want the controllers accessible from the public internet
but just the office IPs. Workers also need to talk to the controller
instances so we allow this too.
Things we weren't sure on:
- do controllers need to be able to talk to other controllers? Things seem to be working without allowing this but we can't be 100% sure that this means it is fine

Restrict access to controller to office IPs

---

example/cluster.tf
example/outputs.tf
example/variables.tf
modules/bootkube-ignition/outputs.tf
modules/flux-release/main.tf
modules/flux-release/variables.tf
modules/gsp-cluster/main.tf
modules/gsp-cluster/network.tf
modules/gsp-cluster/outputs.tf
modules/gsp-cluster/route53.tf
modules/gsp-cluster/variables.tf
modules/k8s-cluster/main.tf
modules/k8s-cluster/security.tf
modules/k8s-cluster/variables.tf

Since the "allowed ips" changes went in the NLB target groups for the kube-apiserver were permanently "unhealthy". This simplifies the security group rules while fixing that problem.
Probably best to review only the commit with the changes as the `terraform fmt` commit modifies lots of unrelated files with whitespace changes.

Fix lb healthchecks

---

bootstrapper/bootstrap.sh

the bootstrapper node currently remains registered as a `Node` object in the cluster... which means things like DaemonSets report back as `NodeLost`. 
This updates the bootsrapper script to `kubectl drain` and `kubectl delete node` the bootstrapper to tidy up.
`--force` and `--ignore-daemonsets` flags are used to make the drain more agressive since this node is def going away, but may not always be required.
I have run the commands manually ... but I haven't tested the script as a whole

drain and delete bootstrapper node when done

---

modules/gsp-cluster/main.tf

If the CI addon is disabled for the cluster it is still attempting to
fetch the bucket name/region etc to populate the values for the
flux-release
This uses the nasty "concat with empty list and get the first element"
technique used elsewhere to workaround the problem

Ignore bucket values when ci-addon disabled

---

modules/flux-release/data/helm-release.yaml
modules/flux-release/main.tf
modules/flux-release/variables.tf

We'd like to be able to distinguish the difference between the
releaseName and the namespace.

Allow releaseName setting

---

modules/gsp-cluster/main.tf
modules/gsp-cluster/variables.tf
modules/k8s-cluster/variables.tf
modules/lambda_splunk_forwarder/iam.tf
modules/lambda_splunk_forwarder/index.js
modules/lambda_splunk_forwarder/lambda.tf
modules/lambda_splunk_forwarder/lib/mysplunklogger.js
modules/lambda_splunk_forwarder/variables.tf

https://trello.com/c/qboQ4xcn/223-ship-logs-from-cloudwatch-into-splunk
- Decision was made to have one lambda per cluster rather than
one lambda per account. This is because the cloudwatch log
group to ship is set up with each cluster and is not known
by the account
- Default is not to ship logs to splunk for the moment as dev
stacks will not need to and EIDAS  only want to ship prod
logs rather than staging (although also want to ship staging
whilst the pen test is ongoing).
The code has been adapted from https://github.com/deliveryhero/dhh-system-engineering/tree/master/terraform/aws/modules/lambda_splunk_forwarder.
Whilst I tried to avoid diverging from the module, I ended up
bringing the code into our repository and adapting it. The reasons
for this are
- there is no way to …

Add lambda to optionally ship cloudwatch logs to splunk

---

modules/gsp-cluster/main.tf
modules/gsp-cluster/variables.tf

When we implement a new feature right now, say add `splunk` into the mix,
we will break any other cluster setup that currently doesn't have that
key embedded.
Instead, we could be having defaults as a different map, and attempt to
merge them when necessary to avoid breaking the cluster.
- Code review - see if I haven't missed `s/var.addons/local.enabled_addons/g`
- Run `terraform apply` against your cluster
- would be good to remove some of the default values
- This could be tested by:
- just modifying the `cluster.tf`
- running `terraform init -upgrade=true`
- running `terraform plan`
- expect `No changes`

Provide real fallback defaults for addons

---

modules/gsp-cluster/data/ci-secrets.yaml
modules/gsp-cluster/main.tf
modules/gsp-cluster/outputs.tf

https://trello.com/c/nZqPwMsF/112-create-a-pipeline-for-promoting-deployment-charts-between-environments
Given that CI pipelines will exist in the default concourse
team (called `main`), k8s secrets that need to be available to
concourse must be placed in the `ci-system-main` namespace.
This is documented in the concourse chart:
https://github.com/helm/charts/tree/master/stable/concourse#kubernetes-secrets
This key is also outputted from the gsp-cluster module as it will
need to be manually copied by a developer and added as a
deployment key with read/write access to the repository which we
allow our CI to have write access to.
This will allow our CI to tag repositories as part of our
deployment pipeline, tagging a `staging` and `production` branch.

Create ssh key so CI can write to github repos

---

modules/flux-release/main.tf

We're now supporting the fallback functionality when it comes to setting
the release_name. This has however been omitted when we need to output
the variable to different means.

Fallback to namespace

---

modules/gsp-canary/main.tf
modules/gsp-canary/scripts/initialise_canary_helm_codecommit.sh
modules/gsp-canary/variables.tf
modules/gsp-cluster/main.tf
modules/gsp-cluster/variables.tf

During initialisation when terraform local-exec's the script to bootstrap
the code commit repo the script itself hasn't assumed the appropriate role
(as terraform has). So, an explicit assume role needs to happen.

Fix permissions for the canary code commit initialisation script.

---

modules/gsp-canary/scripts/initialise_canary_helm_codecommit.sh

Whilst the command works beautifully on macOS, I'm not sure how did it
ever work in the docker container in the pipeline.
The Linux version of sed doesn't understand the empty string straight
after the `-i` flag unless the empty white space would not be present.
The macOS version, will be happy with the said white space but it will
throw up if it's missing...
Since we're deliberately `git add`ing the file we want in the shell
script, we can make the best of both world and convert the flag to
`-i.bak`, which as a side effect will create a backup file, but will
work on either OS.
I care about both OS, as the script is ran in the pipeline (Linux) for
automated deployment, but also on our local machines (most likely
macOS), to spin the personal cluster up.
- Run command on your machine
- Run …

Allow sed work cross OS

---

modules/gsp-ci/iam.tf

Right now, if the CI module is disabled in the terraform, it will fail
to run the `apply` action due to an empty array and code "compilation".
Appending every array with an empty entry should fix that issue.
- Seek sense in my thinking
- Attempt to build non-ci cluster from master - `terraform plan`
- Attempt to build non-ci cluster from this branch - `terraform plan`

Disable data resource generation by default

---

modules/gsp-cluster/main.tf
modules/gsp-cluster/outputs.tf
modules/gsp-cluster/secrets.tf

We'd like to avoid the need of re-encrypting the secrets if say a
cluster had to be re-built.
This will make it harder to rotate that key for the cluster, as the code
will have to be commented out, applied and then destroyed, but it's a
necessary evil.
This also means that when any plan that includes a destroy of this
resource will return an error message, which is going to affect our
pipelines and perhaps cause a lot of confusion when the day comes.
It should however mean, that the actual key is going to persist in
terraform state file.
1. Code review
1. Spin up the cluster pointing to this branch
1. Seal a random thing
1. Apply sealed secret to the cluster
1. See if it's decrypted properly
1. Tear down the cluster (should fail on that two resources)
1. Spin up the cluster pointing to …

Persist key for SealedSecrets

---

modules/gsp-cluster/secrets.tf
modules/gsp-cluster/variables.tf

Our sandbox accounts suffer from not being able to be torn down. We can
fix that by pointing to a different branch that will disable the
prevention.
If that's the case, we can provide the terraform with a variable, that
will set it for us. By default, prevent deletion, but if it's a sandbox
correctly configured, it should have an additional flag.
- Sanity check
- Optionally, setup your cluster with additional flag and tear it down
- Add `prevent_sealed_secret_destroy = true` to your `gsp-cluster` module configuration in `gsp-teams`

Allow disabling destroy prevention

---

modules/gsp-cluster/main.tf

This will not apply the values cleanly, meaning the kube resource will
fail to be applied. In fact, it may stop flux applying anything at all,
which caused a problem in our sandbox clusters...
I'm sorry...
- Code review
- Apply from this branch to your cluster
- Expect everything working properly

Fix the indention

---

modules/flux-release/data/namespace.yaml
modules/flux-release/main.tf
modules/flux-release/variables.tf
modules/gsp-cluster/data/cert-manager-crds.yaml
modules/gsp-cluster/main.tf

- We need to apply the `cert-manager` CRDs ourselves [1].
- We have to disable some `cert-manager`-specific validation in the
`ingress-system` namespace [1].
- We have disabled the webhook. The webhook currently fails to install
and was not installed by default in version 0.5.2 of the `cert-manager`
chart. It appears as though enabling Aggregation Layer Routing may solve
the problem [2,3].
[1] https://github.com/helm/charts/blob/2978da57109b37351f9d032fb0a73a976e56cf20/stable/cert-manager/README.md#installing-the-chart
[2] https://github.com/jetstack/cert-manager/issues/1220
[3] https://kubernetes.io/docs/tasks/access-kubernetes-api/configure-aggregation-layer/#enable-kubernetes-apiserver-flags

Upgrade to the latest version of `cert-manager`

---

modules/gsp-cluster/outputs.tf
modules/k8s-cluster/outputs.tf

We need to allow HSM Client (hosted on the worker) to interact with the
HSM itself. This runs on a private network, meaning we need to allow
some inbound access.

Expose worker's security groups

---

modules/k8s-node-ignition/data/kubelet.service

Kubernetes is deprecating the read-only, insecure kubelet port in favour
of the secured port. This allows prometheus to monitor the state of the
kubelets properly.

Enable webhook authentication and authorisation for the kubelet.

---

modules/gsp-cluster/data/flux-reporter.yaml
modules/gsp-cluster/data/flux.yaml
modules/gsp-cluster/main.tf

We'd like to be running a version of flux that will tell us exact commit
that is running at the current time on the cluster.
It targets the PR we have raised, and hopefully should soon be
pointing back to upstream images...
As part of flux deployment, we'd be running the reporter application to
monitor what is currently deployed.
This should in future be built from a chart along with the flux, but
we're not there yet.
It has became a problem since version [0.5.2][1], where there was a change
to when how flux will run `helm update`. This is causing a problem with
fluentd-cloudwatch dependency as it's an incubator project...
We don't care for the updates done automatically by flux. We'd like to
disable this.
This however highlights the problem, that we have a hardcoded set of
charts for …

Upgrade Flux and add Flux-Reporter

---

modules/bootkube-ignition/data/manifests/aws-iam-authenticator-cfg.yaml
modules/bootkube-ignition/manifests.tf
modules/bootkube-ignition/variables.tf
modules/gsp-cluster/data/sre-cluster-role.yaml
modules/gsp-cluster/iam.tf
modules/gsp-cluster/main.tf
modules/gsp-cluster/variables.tf

This role gives read-only access to most things (via the built-in
Kubernetes `view` role) but does not grant access to Secrets[1].
We extend the `view` role with some additional non-read actions that are
useful for day-to-day SRE-ing.
We will almost certainly have to add more non-read actions as we
discover more things that SREs do regularly.
[1] https://kubernetes.io/docs/reference/access-authn-authz/rbac/#user-facing-roles
Co-authored-by Sam Crang <sam.crang@digital.cabinet-office.gov.uk>
Co-authored-by David Pye <david.pye@digital.cabinet-office.gov.uk>

Add role for general SRE use

---

modules/gsp-cluster/iam.tf

This allows admins to assume a role with _less_ access if they choose.
This also means that our Principal will always be populated with
something. Without this change if a cluster doesn't specify any
`sre_user_arns` a `terraform apply` will fail because of a malformed
policy document.
Soz m8s

Allow the `admin` role to assume the `sre` role

---

modules/flux-release/data/helm-release.yaml
modules/flux-release/main.tf
modules/flux-release/variables.tf
modules/gsp-cluster/data/flux.yaml

We implemented verification of commit signatures against a list of
known public keys in the flux helm operator.
These changes are unlikely to make it upstream in the short term so we
are building and using images from our own fork[<sup>1</sup>][1]
---
[1]: https://github.com/alphagov/gsp-flux
<sup>1</sup> https://github.com/alphagov/gsp-flux

Commit verification for flux-release module

---

modules/flux-release/main.tf

We're using flux system everywhere wheather or not the release is
enabled.
This causes issues when for instance `ci-system` is disabled in one of
the clusters and still generates the key that it's confused what to do
with it.
It's a technical debt and should go away in the future.

Add count for SSH key generation

---

modules/flux-release/data/helm-release.yaml

We pass in cluster.name and cluster.domain as useful vars for use in
writing helm charts that need to know the base domain pointing at the
cluster.
To make these more useful for nested charts (that cannot read the
top-level values) we want to pass these in as helm global values[1]
[1] https://github.com/helm/helm/blob/master/docs/chart_template_guide/subcharts_and_globals.md#global-chart-values

Set cluster name/domain as global helm vars

---

modules/gsp-ci/data/web-configmap.yaml
modules/gsp-ci/main.tf
modules/gsp-ci/secrets.tf
modules/gsp-ci/variables.tf
modules/gsp-cluster/main.tf
modules/gsp-cluster/variables.tf

We'd like to allow people to view concourse on their laptops and
dashboard screens without the need of using `kubectl port-forward`
therefore we need to make sure we're not just handing username and
password left and right.
After hardening the login credentials, we're in a better position to
expose concourse to the world.
Managing users is hard and we'd like to put that burden on a third party
oauth provider, which happens to be GitHub.
- Code review & Sanity check
- Deploy CI system to a cluster with some GitHub credentials provided

Expose Concourse to the world

---

modules/gsp-ci/variables.tf
modules/gsp-cluster/variables.tf

We'd like to be dependant on GitHub and fail running terraform if the
client credentials are not passed in.

"Why you adding options to things?"

---

modules/gsp-ci/data/web-configmap.yaml

We've been relying on backwards compatibility, which is sadly deprecated
in favour of this roles file. The owner/admin user is no longer assigned
to any team automatically, meaning we get a nice error message when we
attempt to use API with this auth.
It is difficult to find this page, so linking it up:
https://concourse-ci.org/managing-teams.html#setting-roles

Define owner role for pipeline-operator

---

modules/gsp-cluster/main.tf
modules/gsp-cluster/variables.tf

Pass through labels for prometheus to add to all alerts before sending
on to alertmanager so they can be routed correctly
we map "product" label to the account_name (ie Verify)
we map "deployment" labal (which is used kind of like an environment
type label) to "gsp"

add external prometheus labels to montioring-sys

---

modules/flux-release/data/namespace.yaml

If we want to be able to use `namespaceSelector`s (for example on
`NetworkPolicies`) then we need to be able to use `matchLabels` which
requires a label on the `Namespace`.

Add `namespace` label to namespaces

---

modules/flux-release/data/namespace.yaml
modules/flux-release/main.tf
modules/flux-release/variables.tf
modules/gsp-cluster/main.tf

With namespaces that we had specified `extra_namespace_configuration`
and that `namespace_configuration` included `labels` we would overwrite
the ones defined previously that added a label with the name of the
namespace.
Fortunately the `extra_namespace_configuration` was only ever used for
setting `labels` so we can easily change it.

Do not specify `labels` twice

---

modules/gsp-cluster/iam.tf

Sadly, there is no strict restriction to only allow CloudWatch access,
but we will need to have read only access to some random bits in the
system. [AWS docs][1]
[1]: https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/iam-identity-based-access-control-cw.html#read-only-access-example-cw
- Sanity check

Allow our SREs access to CloudWatch

---

pipelines/deployer/deployer.yaml
pipelines/examples/clusters/sandbox.yaml

we have a "real" environment now, and that destroy job is real tempting
this moves the job to another group reduce change of an accident... we
may want to completely remove this job from persistant clusters

use groups to make destroy less appealing

---

charts/gsp-cluster/templates/00-aws-auth/sre-cluster-role.yaml

As an sre I want to be able to debug the cluster configuration in detail, including rbac roles and istio network configuration.
This grants `get`, `list` and `watch` permissions to prettymuch all resources in istio and also to nodes and rbac.

grant sre role read-only permisisons to istio/rbac/nodes

---

pipelines/deployer/deployer.yaml
pipelines/examples/clusters/sandbox.yaml

we need to be able to configure the cluster sizing and node sizing from
the pipeline. this exposes the terraform variables for
ci_worker_instance_type, ci_worker_count, worker_instance_type and
worker_count from the concourse input variables.

parameterise setting the node instance types/count

---

modules/gsp-cluster/main.tf
modules/k8s-cluster/main.tf
modules/k8s-cluster/variables.tf

Some pods were being scheduled onto nodes in the public ranges preventing
them from accessing certain AWS resources that were protected by security
groups (e.g. CloudHSM). No workers should be instantiated in the public
subnets.

Restrict node groups to private IP subnets.

---

hack/set-deployer-pipeline.sh
pipelines/deployer/deployer.yaml

with cluster names being the same as account names we get weird
generated cluster-domains like portfolio.portfolio.govsvc.uk.
to avoid this while not being too prescriptive about exactly what the
domains are we are allowing setting the cluster domain manually from the
deployer pipeline.
Related: https://github.com/alphagov/gsp-teams/pull/147

allows setting cluster-domain from cluster config

---

modules/gsp-cluster/alb.tf

cannot delete cert while attached to ALB, use create_before_destory to
do things in the right order

fix ordering of cert deletion

---

modules/gsp-cluster/data/values.yaml
modules/gsp-cluster/values.tf

concourse password was being "quoted" in an incorrect way causing the
pipeline operator to be passed a different password to what concourse
web was using

fix extranous quotes around concourse password

---

charts/gsp-cluster/templates/02-gsp-system/pipeline-operator-role.yaml

concourse operator now looks after Team resources too so this adds the RBAC to let it do it's thing

adds rbac for conc controller to handle teams

---

charts/gsp-cluster/templates/03-namespaces/namespace.yaml
hack/lint-terraform-values-output.sh

each namespace will get its own concourse team, and access will
be granted to the github users who have the appropriate roles assigned
example:
a namespace called "sandbox-myapp" in the "sandbox" cluster would get a
concourse team called "myapp" created.
user with role "sandbox-sre" or "sandbox-myapp-dev" will get
pipeline-operator role assigned for the concourse team.
Note: the hack/lint script is just a hacky thing for rendering out the template so you can look at it, not used for anything serious
So that we can use the same user roles/namespacing to segregate concourse usage

generate concourse teams for each namespace

---

pipelines/deployer/deployer.yaml

We'd like to be applying only specific configuration files to each
cluster. We're reserving a name global, for potential shared
configuration such as canary.
- Sanity check
- Apply and run pipeline ¯\\\_(ツ)\_/¯

Make namespace selection smarter

---

pipelines/deployer/deployer.tf

We noticed that some vars are not defined and so are invalid when using fly to push a pipeline for test. We've set defaults of empty strings.
@smford 
@szd55gds

add some empty defaults to splunk vars

---

modules/gsp-cluster/vpc-flow-logs.tf

It should be a plural: vpc-flow-logs.amazonaws.com

Fix typo in vpc flow logs principal

---

pipelines/deployer/deployer.tf

Error messages from missing parameter values will be a much clearer indication of a missing variable than silently succeeding and trying to diagnose why logs aren't appearing where we expect them to.
Fail fast and explicitly.

Revert "add some empty defaults to splunk vars"

---

README.md
docs/gds-supported-platform/getting-started.md
scripts/gsp-local.sh
scripts/local-values.yaml

You should be able build and push an image with a pipeline that looks something like this:
```
resource_types:
- name: harbor
type: docker-image
privileged: true
source:
repository: govsvc/gsp-harbor-docker-image-resource
tag: "0.0.1558617848"
- name: github
type: docker-image
privileged: true
source:
repository: "govsvc/concourse-github-resource"
tag: "0.0.1551114195"
harbor_source: &harbor_source
username: admin
password: Harbor12345
insecure_registries: ["registry.local.govsandbox.uk:80"]
harbor:
url: http://registry.local.govsandbox.uk
prevent_vul: "false"
enable_content_trust: "false"
enable_notary: "false"
notary:
url: http://notary.local.govsandbox.uk
root_key: ""
delegate_key:  ""
passphrase:
root: ""
snapshot: ""
targets: ""
delegation: ""
resources:
- name: foo-repo
type: git …
```

Local Concourse and Harbor

---

modules/hsm/main.tf

Since moving this code from gsp-teams into gsp-terraform-ignition this
no longer needs to be a fixed remote link. It can update in line with the
rest of the repo.

Update location of splunk forwarder module.

---

modules/lambda_splunk_forwarder/lambda.tf

forwarding lambda is timing out causing missing logs in splunk ...increasing the timeout to 60s to give it a bit more time.

Increase lambda forwarder timeout

---

modules/gsp-cluster/monitoring-system.tf
modules/k8s-cluster/iam.tf
modules/k8s-cluster/outputs.tf

SSM, it turns out, doesn't require the majority of the permissions
afforded it by the AWS managed policy. So use a stripped down version
that is enough to allow SSH from the AWS Console Session Manager.
Spot tested using Session Manager to SSH to one of each worker group. Also checked that the kiam server was pushing logs to CloudWatch.

Reduce permissions granted to all worker nodes.

---

Brewfile
docs/gds-supported-platform/getting-started.md

- Brewfiles mean that users can run `brew bundle` instead of individual `brew
install` commands.
- Edit the docs to note that we're now getting dependencies from the Brewfile.
- I also noticed \`aws-vault\` elsewhere, so I've added it.

Add a Brewfile to make installing pre-requisites easier

---

charts/gsp-cluster/templates/04-main-team-pipelines/cd-smoke-test-pipeline.yaml

we want the smoke tests that check the continuous delivery stuff
(concourse, harbor, k8s, github etc) all work periodically.
we want this in ALL the clusters so make it part of the gsp-cluster
chart
we use the "main" team becuase this is not team specific

moves the canary deployment to main team

---

docs/gds-supported-platform/getting-started.md

Since we are now using minikube the 'kind' piece to upload a docker container no longer works. The replacement code suggestions are tested and work fine on a stock gsp-local built from 'master' branch.

replace the 'kind' command with a sequence effecting the same outcome

---

pipelines/deployer/deployer.yaml

This requires a [custom version of the k8s acceptance tests](https://github.com/alphagov/kubernetes/tree/allow-node-count) (instructions for building in commit) and an [unreleased version of Sonobuoy](https://github.com/alphagov/gsp-docker-images/pull/16).

Run a subset of the k8s e2e tests with Sonobuoy

---

pipelines/deployer/deployer.yaml

The `github` resource requires a PR with a minimum number of approvals.
This makes changes to the sandbox cluster (and possibly other places
where we need to iterate quickly) awkward.
This change replaces the `github` resource with the `git` resource in
the sandbox cluster.

Allow sandbox cluster to have less restrictive deployments

---

pipelines/deployer/deployer.yaml

- Something weird is going on when `cat`-ing all the files together
before pushing it through `yq`
- `yq` can take a list of files to parse so we can just use that instead
with CLUSTER_NAME=verify
```
cat *.yaml | yq . | jq -c -s "[.[] | select(.roles[] | select((. == \"${CLUSTER_NAME}-sre\" ) or (. == \"${CLUSTER_NAME}-admin\"))) | .github] | unique"
["blairboy362","chrisfarms","paroxp","poveyd","samcrang","smford","szd55gds"]
```
```
yq . *.yaml | jq -c -s "[.[] | select(.roles[] | select((. == \"${CLUSTER_NAME}-sre\" ) or (. == \"${CLUSTER_NAME}-admin\"))) | .github] | unique"
["adityapahuja","andy-paine","blairboy362","chrisfarms","issyl0","paroxp","philandstuff","poveyd","sakisv","samcrang","smford","stephengrier","szd55gds","tlwr"]
```

BAU: Use yq to read files

---

modules/gsp-cluster/canary-system.tf

The GSP has moved repos from gsp-canary-chart to gsp-canary.
Solo: @smford

Move gsp-canary-chart repo to gsp-canary

---

modules/gsp-cluster/scripts/initialise_canary_helm_codecommit.sh

GSP Canary no longer uses codecommit, this is a temporary
fix to re-open the deployment pipelines until use of
codecommit is fully removed.
Solo: @smford

Fix path to values.yaml for the new gsp-canary repo

---

modules/gsp-cluster/scripts/initialise_canary_helm_codecommit.sh

Fix typo:
Wrong: gsp-canary/charts/values.yaml
Right: gsp-canary/chart/values.yaml
Solo: @smford

Fix typo in pathname of chart

---

hack/set-deployer-pipeline.sh
pipelines/deployer/deployer.yaml

* fix: sort user names/keys when set-pipelineing or self-updating so you don't get weird diffs when applying
* feature: allow passing in fly args to set-pipeline so that you can add things like `--var disable-update=true` when pinning to different branch

set-pipeline: Sorting user keys and passing fly args

---

modules/gsp-cluster/splunk-system.tf
modules/k8s-cluster/main.tf
modules/k8s-cluster/outputs.tf

* Adds lambda to ship control-plane logs to splunk.
* Creates the eks log group ahead of time
eks automatically creates a log group for things like the audit logs, we need to create it upfront before eks gets a chance so we can reference it.
⚠️ This will NOT apply cleanly, we will need to hijack pipeline containers for each cluster and manually run:
```
terraform import aws_cloudwatch_log_group.eks /aws/eks/${CLUSTER_NAME}/cluster
```
after this is merged and the manual import is applied we will need to revert the TMP commit

Add splunky audit lambda

---

modules/gsp-cluster/splunk-system.tf
modules/k8s-cluster/main.tf

In [part 1](https://github.com/alphagov/gsp-terraform-ignition/pull/173) we had to TMP drop a `depends_on` and do some manual `terraform import`ing
in part 2 we revert the TMP bit and rename the lambda for clarity

Splunky audit logs (part two)

---

pipelines/deployer/deployer.yaml

cluster-values sometimes has somewhat sensitive data in it, probably better to keep it out of any build logs.

stop leaking cluster-values in task output

---

charts/gsp-cluster/templates/04-main-team-pipelines/cd-smoke-test-pipeline.yaml
pipelines/deployer/deployer.yaml

After we have deployed either entire cluster or marely the canary
successfully, we should expect it to be accessible from outside world.
This should assure us that we are capable of providing traffic into the
cluster - our ingress works and is wired up correctly with *LB of a sort.
- Code review
- Run the docker image `docker run --rm -it govsvc/task-toolbox:1.2.0`
- Run the curl command from inside the container
- Try to change URL to see if it fails properly

Add VirtualService testing to the SmokeTest

---

docs/gds-supported-platform/getting-started-gsp-local.md

So that the docker-machine-driver-hyperkit instructions are actually shown. Per Issy.

Use --verbose flag with brew bundle

---

charts/gsp-cluster/templates/03-namespaces/namespace.yaml
charts/gsp-cluster/values.yaml
pipelines/deployer/deployer.yaml

currently teams have to add any kubeyaml to initialize namespaces to
the "gsp-teams" repo.. these initial resources are usually pipelines and
secrets that kick of other deployments.
we have seen several issues with this centralized approch:
* Teams are used to having their stuff managed in their own repo and
don't see the benefit of having it centralized
* There is no visibility of deployment by service teams since these
resources are deployed by the main deployer pipeline which is not easily
visible to non SREs
* A change to any resource requires a complete platform deployment which
is a massive overkill
* The current implementation for passing the namespace yaml into the
gsp-cluster chart by concatanating the files and then running them
through helm templating is very fragile and error …

Namespace update pipelines

---

charts/gsp-istio/values.yaml

This enables "permissive" mTLS which is how production happens to be
currently working. This setting is not immediately applied and relies on
the `istio-security-post-install-*` job not being deleted. If this job
were to be deleted in production then strict mTLS would be enabled.

Disable strict mTLS

---

hack/set-deployer-pipeline.sh

set-pipeline script would give different behaviour than the update
pipeline causing it to incorrectly remove users

makes set-pipeline script consistant to selfupdate

---

pipelines/deployer/deployer.yaml

This enables cloudwatch acceptance tests on a cluster by discovering the latest log received by cloudwatch.
This test run from the central concourse against a cluster after deployment has occured.
Work was done to integrate this functionality within sonobuoy as a plugin, but was deemed unfeasible as the complexity of implementing and maintaining it would cause signicant issues going forward.  Testing so far has also shown sonobuoy to be somewhat flakey.
Reasons why sonobuoy was not chosen as the acceptance test technology:
1. Issues and complexity around passing secrets in to sonobuoy to allow certain tests to be run
1. The wrapping framework of sonobuoy makes it challenging to pass in arguments to direct tests
1. The learning curve of sonobuoy to implement tests is high
1. To build tests …

Enable Cloudwatch Acceptance Tests

---

charts/gsp-cluster/templates/02-gsp-system/pipeline-operator-role.yaml
charts/gsp-cluster/templates/02-gsp-system/pipeline-operator-svc.yaml
charts/gsp-cluster/templates/02-gsp-system/pipeline-operator-webhook-secret.yaml
charts/gsp-cluster/templates/02-gsp-system/pipeline-operator.yaml
charts/gsp-cluster/values.yaml

Updates the concourse-operator to a version that includes a validating webhook for pipeline CRDs
This should make it so that invalid pipelines fail at `kubectl apply` time and so surface errors early.
⚠️ depends on https://github.com/alphagov/gsp-concourse-operator/pull/10
Without validation we often see the operator stuck in a loop of attempting to apply an invalid pipeline config. There is no visibility into this failure other than checking the logs (which is impractical for users without access to platform logs) and no way to delete the invalid Pipeline (since the finalizer cannot run)

Enable validation webhook for Pipeline resources

---

pipelines/deployer/deployer.yaml

This allows customisable values to be passed to helm which can then be used to overide default cluster values when templated.
Pair: @smford & @samcrang

Enable customisation of values being passed to helm

---

charts/gsp-cluster/templates/02-gsp-system/cloudhsm-service.yaml

This allows for CloudHSM to be exposed by HAproxy, and whitelisted to only allow connections from GDS IPs and internal components of the kuberentes cluster.
To enable CloudHSM a cluster needs to be passed: ```cloudHSMExpose: true```
Pair: @samcrang & @smford

Enable the ability to Expose CloudHSM to GDS IP Range

---

modules/k8s-cluster/main.tf
pipelines/deployer/deployer.tf
pipelines/deployer/deployer.yaml
pipelines/deployer/main.tf

It is possible, that inappropriate use of terraform by say, resorting or
renaming resources could cause a cluster to be destroyed. We don't want
to do that, whilst running ordinary `terraform apply` with some changes.
Adding the option to prevent_destroy, will help to avoid terrafrom being
all jolly about removing the control plane. This however will break the
`destroy` Concourse pipeline, as it will no longer be capable of
performing its job.
Additionally, we probably do care about the log group from the EKS.
Now that we are not allowing accidental removal of the EKS cluster, the
pipeline is broken.
A way to solve it, is to clear out the config file and performing an
apply action on it against the same account. This should trigger
destroyment, and ignore any `prevent_destroy` settings …

Prevent accidental destroy

---

modules/gsp-cluster/outputs.tf
modules/hsm/main.tf
modules/k8s-cluster/outputs.tf
pipelines/deployer/deployer.tf

we want to limit the scope of what can connect to the hsm to only the worker nodes
so that protective monitoring around hsm connectively can be more effective
* ⚠️  Untested, so should try in sandbox to check doesn't cause HSM to be destroyed! (it shouldn't!)

limits hsm ingress to only from worker nodes

---

charts/gsp-cluster/templates/00-aws-auth/aws-vpc-cni.yaml

Disables the SNAT feature of the VPC CNI so that Pod traffic communicates directly without traversing nodes.
Before/Current:
After/Future:
We were having trouble adding protective monitoring that made us of the
VPC Flow logs as _sometimes_ traffic was getting routed to external
services also in the private VPC via the primary node interface(s)
instead of what we expected to see as coming directly from the Pod addr.
By default, the Amazon VPC CNI plugin for Kubernetes configures pods
with source network address translation (SNAT) enabled. This sets the
return address for a packet to the primary public IP of the instance and
allows for communication with the internet.
SNAT is only required for nodes that reside in a public subnet but our
nodes reside in private subnet and connect to the …

Disable SNAT of Pod network traffic (VPC CNI)

---

pipelines/deployer/deployer.yaml

At the moment, the canary could have been deployed once and then fail
thereafter. Kubernetes will keep it up despite it further attempts to
re-deploy it. This means we cannot rely on the ping only.
The `/metrics` endpoint exposes the timestamp of when the canary has
been deployed.
We can read that entry and attempt to find out if it has been deployed
in the past N minute slot. That will assure us, that it has in fact been
re-deployed.
- Run the above command locally pointing to a live canary
- Expect `exit 0`
- Change the command to do `-ge` comparison instead
- Expect `exit 1`

Check if Canary has been deployed recently

---

scripts/gsp-local.sh

When running our product in GSP local, we need more CPU and memory. This will allow us to set environment variables to get a bigger GSP cluster.

BAU: allow customisation of local GSP resource allocation

---

charts/gsp-cluster/templates/02-gsp-system/cloudhsm-service.yaml

From the HAProxy docs[1] for `server`:
```
<port>    is an optional port specification. If set, all connections will
be sent to this port. If unset, the same port the client
connected to will be used.
```
[1] https://cbonte.github.io/haproxy-dconv/1.9/configuration.html#4.2-server

Expose all CloudHSM ports in sandbox cluster to the office

---

charts/gsp-cluster/templates/02-gsp-system/cloudhsm-service.yaml

Multi-port services must have names[1]:
```
For some Services, you need to expose more than one port. Kubernetes
lets you configure multiple port definitions on a Service object. When
using multiple ports for a Service, you must give all of your ports
names so that these are unambiguous.
```
[1] https://kubernetes.io/docs/concepts/services-networking/service/#multi-port-services

Fix Service resource

---

modules/gsp-cluster/data/values.yaml

When we deploy Harbor in our release pipeline on shared concourse, we're
running `helm template`. This causes some of the values to be generated.
The newly templated app is then kube cuttle applied to the system, and
perhaps does not roll all the boxes properly - as a version of a chart
hasn't really changed.
This is potentially causing a problem we are experiencing, where each
run of the release pipeline breaks the Registry. The solution often is
to kick the containers that haven't been restarted thus far and it will
sort itself out.
By hardcoding / re-using the secret, we hope for it to persist through
all deployments, making our lives easier and preventing the need to kick
the containers into good shape.
https://github.com/goharbor/harbor-helm/blob/master/values.yaml#L291-L294 …

Re-use the secret for different components

---

modules/k8s-cluster/data/nodegroup.yaml

we don't want our nodes to have public ip addresses assigned, they live
in a private subnet and have a NAT gateway so assigning a public IP is
kind of pointless and maybe even presents a risk of accidental
misconfiguration
⚠️ untested, run through sandbox first

disable assignment of public ip addr to nodes

---

modules/gsp-user/iam.tf

At the moment, each user is capable of getting onto the AWS account and
dig through the CloudWatch logs. This is however restricted to the CW
itself and does not include CloudWatch Insights.
We can replace manually created actions with a policy that is attached
to the user, that should give everyone readonly access to everything and
is managed by AWS themselves.
There is no reason for people not to have a very limited access to the
resources used on AWS.
New role allows only for Describing and Listing different pieces of
infrastructure and should prevent things like s3:GetObject from
happening accidentally.
This policy is managed by AWS meaning we have to worry less (?).
- Sanity check

Improve CloudWatch access

---

pipelines/deployer/deployer.yaml

Sends github PR checks to verify that the PR meets the correct approval rate
Because it's annoying finding out too late that you weren't on the list of trusted developers

adds a pull-request resource to check for trusted-developers

---

modules/gsp-user/iam.tf

aws_iam_role_policy_attachment is non exclusive

uses aws_iam_role_policy_attachment for gsp-users

---

pipelines/deployer/deployer.yaml

we now have a values.yaml in each cluster config repo, so we can now be explicit and not rely on some scripting hackery to put it in the right place.
this does mean that the ${ACCOUNT_NAME}-main team must be explitictly set as part of the values otherwise concourse will be upset (since concourse likes the -main team to exist)
previously we scripted the extraction of the namespace values from concourse vars (cluster.yaml) added a ${ACCOUNT_NAME}-main team to the list and then passed them along to the helm template
Please merge these:
* https://github.com/alphagov/verify-cluster-config/pull/8
* https://github.com/alphagov/tech-ops-cluster-config/pull/217

removes generate-namespace-values task

---

charts/gsp-cluster/values.yaml

Disables prometheus exporters/ServiceMonitors for the etcd, controller-manager, and
scheduler components
EKS manages etcd, controller-manager and scheduler in a way that is not observable via the usual kubernetes means, this results in false alerts from prometheus spamming our channel which is configured to expect to find them in the cluster. 
⚠️ Manual intervention required
It is very likely that this will leave the old `ServiceMonitor` records laying around in `gsp-system` that will need manually deleting.

disable exporters for eks managed components

---

components/concourse-operator/Dockerfile
components/concourse-operator/Gopkg.lock
components/concourse-operator/Gopkg.toml
components/concourse-operator/pkg/webhook/default_server/pipeline/validating/pipeline_create_update_handler.go
components/concourse-operator/pkg/webhook/default_server/pipeline/validating/pipeline_create_update_handler_test.go

* updates the dep depenedency constraints to pull in an up to date version of concourse/atc lib
* adds a basic validation test
* fixes Dockerfile for builds without vendor dir
Because currently you cannot kubectl apply a Pipeline that has any recent concourse 5 features in it like `in_parallel`  (See https://github.com/alphagov/gsp/issues/231)
Fixes #231

Fix pipeline validation for concourse v5+ configs

---

modules/hsm/main.tf
pipelines/deployer/deployer.tf

Due to:
https://github.com/terraform-providers/terraform-provider-aws/issues/8648
and the inability to scale an HSM cluster out from terraform it makes
sense to not manage the cloudHSMs from terraform.
For each `-deployer` pipeline:
1. Run `deploy` job and hijack the `cluster-state` container
1. `terraform state rm module.hsm.aws_cloudhsm_v2_hsm.cloudhsm_v2_hsm`
Then:
1. Pause all relevant `-deployer` pipelines on https://cd.gds-reliability.engineering/
1. Merge
1. Un-pause all pipelines

No longer use terraform to manage the state of the cloudHSMs.

---

docs/gds-supported-platform/prometheus_alert_manager_grafana.md
pipelines/deployer/deployer.yaml

Add acceptance test to check that Prometheus and Grafana port forwarding works, as is asserted in our documentation.
Change 'Set up monitoring and alerting' docs to reflect change from `monitoring-system` to `gsp-system`.
Resolves https://github.com/alphagov/gsp/issues/199

Add acceptance test for Prometheus and Grafana port forwarding

---

Brewfile

- Some people with Linux laptops use Homebrew on Linux as a package
manager. Now, they can use this Brewfile to `brew bundle` the
the required dependencies for this project.
- Hyperkit and related formulae only work on MacOS, but there are now
Linux formulae for aws-vault and minikube.
Note that in order for GSP Local to run on Linux with easy dependency install with `brew bundle`, this will also need VirtualBox or `docker-machine-driver-kvm2` packages (the former is again shipped as a Cask for MacOS), but I don't have the time to add them to Homebrew on Linux right now. This gets us _some_ of the way at least, and the rest of the pre-requisites are left as an exercise for the next person to try this. :-) GSP Local won't work on Linux yet anyway, even with new docs, as …

Brewfile: Support Linux use too

---

components/concourse-github-resource/assets/in

removes the lines that dump the config 'payload' whenever it encounters a configuration error
it's possible that the configuration contains sensitive information (like the github api key) which should not find it's way into the concourse build logs (see https://github.com/alphagov/gsp/issues/204)
⚠️ New image has not been built/pushed ... maybe wait for https://github.com/alphagov/gsp/pull/230 before merging

stops dumping resource config on error

---

charts/gsp-cluster/templates/03-namespaces/namespace.yaml

* Adds a default deny-all ingress NetworkPolicy to user namespaces (gsp-system, kube-system, istio-system should be unaffected)
* Add a default-allow rule for prometheus to talk to pods
* We should require people to be explicit from the start about whitelisting NetworkPolicy
* We need prometheus to be allowed to scrap all the envoy instances (and potentially user instances) so that we can monitor them correctly
* proxy-node currently has it's own default deny that is identical to this, we should remove it
* I considered adding a default "allow from istioingress" rule too ... but this didn't feel quite right... this means everyone will need to whitelist istioingress :/

Default deny-all NetworkPolicy for user namespaces

---

charts/gsp-cluster/templates/03-namespaces/namespace.yaml

Allow layer4 traffic from ingressgateway pod by default
we expect most things to need ingress from ingressgateway so we allow this.
we recently added a default-deny rule, but this broke all ingress (see failing canary)

allows ingress from ingressgateway to user namespaces by default

---

modules/gsp-cluster/main.tf
modules/k8s-cluster/iam.tf
modules/k8s-cluster/variables.tf

Otherwise this happens:
`Error: resource 'aws_iam_role.aws-service-operator' config: unknown resource 'data.aws_iam_policy_document.trust_kiam_server' referenced in variable data.aws_iam_policy_document.trust_kiam_server.json`

Pass KIAM trust policy JSON into k8s-cluster

---

charts/gsp-cluster/templates/02-gsp-system/harbor-notary-secret.yaml

- GSP Local users were getting the following error message due to these
values being empty:
```
error: error validating "/var/folders/jr/lv1mpg4s6cgby621kx99vjfm0000gr/T/tmp.oZlkGF5l/gsp-cluster/templates/02-gsp-system/harbor-notary-secret.yaml": error validating data: [unknown object type "nil" in Secret.data.ca, unknown object type "nil" in Secret.data.crt, unknown object type "nil" in Secret.data.key, unknown object type "nil" in Secret.data.tls.ca, unknown object type "nil" in Secret.data.tls.crt, unknown object type "nil" in Secret.data.tls.key]
```
- The problem is b64enc requires a non-empty string, and it's getting
just that from charts/gsp-cluster/values.yaml.
- Outside of GSP Local, these values are loaded from Terraform. But
within GSP Local, Terraform doesn't run.
- Fixes …

Fix gsp-local error due to empty values in harbor-notary-secret.yaml

---

charts/gsp-cluster/templates/00-aws-auth/dev-cluster-role.yaml
charts/gsp-cluster/templates/00-aws-auth/sre-cluster-role.yaml

Appears to be required to seal secrets.
Might fix #271, should at least give us a different error message.

Allow non-admin users to get services/proxy

---

scripts/gsp-local.sh

- Hyperkit is a macOS-only thing. Users on Linux need to use a different
`--vm-driver` setting for Minikube, either `virtualbox` or `kvm2`.
- I didn't find a good place to put this in the gsp-local docs, so Linux
users can make do with reading the code when they get the "unsupported
driver" error by default. ;-)

gsp-local: Use VM_DRIVER envvar for non-macOS users to set

---

pipelines/deployer/deployer.yaml

Replace "apply empty terraform" with "destroy from current state". Several manual clicky-clicky steps in the console (requires admin) but that's acceptable for now.

Fix destroy pipeline

---

charts/gsp-cluster/templates/01-aws-system/aws-service-operator.yaml
charts/gsp-cluster/values.yaml
modules/gsp-cluster/iam.tf
modules/gsp-cluster/main.tf
modules/gsp-cluster/values.tf
modules/k8s-cluster/iam.tf
modules/k8s-cluster/variables.tf

DCS are likely to be using this to create SQS queues, which will replace RabbitMQ.
This is mostly from AWS, with a fix or two.

Add AWS Service Operator, for use by DCS

---

charts/gsp-cluster/templates/02-gsp-system/calico.yaml

- Issy is raising this as @poveyd isn't around today.
https://trello.com/c/Phfs3tRa/2-resolve-cputhrottlinghigh-alert-on-verify-gsp

Remove Calico autoscaler, as requested, to resolve cpu alerts.

---

charts/gsp-cluster/templates/03-namespaces/namespace.yaml

- These need `username` and `password` keys (the password being the
GitHub API token because 2FA).
Co-authored-by: Philip Potter <philip.potter@digital.cabinet-office.gov.uk>

Add parameters to be able to clone private repos over HTTPS

---

charts/gsp-cluster/templates/01-aws-system/aws-service-operator.yaml

If we're running locally we don't want to (and can't) run the AWS
service operator.

Don't run AWS service operator unless it's in AWS

---

charts/gsp-cluster/templates/04-main-team-pipelines/cd-smoke-test-pipeline.yaml

The canary deploy job got stuck for 6 days in sandbox, when normally
it takes ~1m.  This adds a timeout so that it will abort if it doesn't
complete in a timely manner.

Add timeout for canary deploy

---

charts/gsp-cluster/templates/03-namespaces/namespace.yaml
charts/gsp-cluster/templates/_helpers.tpl
charts/gsp-cluster/values.yaml

This only makes them private in the sense that anonymous users are unable
to pull images from that repository; but it does potentially open up a
security hole around the harbor registry's admin credentials, which are
used to deliver this.
If we trust the 2-eyes process, then this shouldn't be a problem.
* Set `public: false` in the harbor resource type in the build pipelines that build the image you want to release privately
* include an `imagePullSecrets` to the pod template as per [k8s docs](https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/#create-a-pod-that-uses-your-secret) with the secret name of `registry-creds`

Facilitate basic private docker repos in harbor registry.

---

charts/gsp-cluster/templates/04-main-team-pipelines/cd-smoke-test-pipeline.yaml
components/canary/chart/templates/deployment.yaml

- For testing whether the private thing works.
Co-authored-by: Daniel Blair <daniel.blair@digital.cabinet-office.gov.uk>

Make the canary Harbor images private via the pipeline

---

charts/gsp-cluster/templates/04-main-team-pipelines/cd-smoke-test-pipeline.yaml

- Then hopefully it gets passed correctly?

Put `public: "false"` in the YAML anchor itself

---

docs/gds-supported-platform/making-things-private-in-harbor.md

Ported from https://github.com/alphagov/doc-checking/pull/173.

Add documentation about configuring images in Harbor to be private

---

Brewfile

- aws-vault was supposed to have been removed in
c7c6a00513dd37110e0dd7b8cfc4b19c5a76c96b.
- Casks are now automatically skipped on Linux, so we don't need this
ugly `if OS.mac?` stuff for them.

Brewfile: Remove aws-vault and the `if OS.mac?` conditional for Casks

---

docs/README.md
docs/architecture/gsp-architecture.md

- Closes #305.
- This link is broken.
- The most likely replacement looks to be
https://github.com/alphagov/gsp/blob/master/docs/architecture/gsp-architecture-local.md,
but that is blank.
- So, just remove the link at all.

Remove dead link to GSP Architecture Local Environment docs

---

charts/gsp-cluster/templates/00-aws-auth/dev-cluster-role.yaml
charts/gsp-cluster/templates/00-aws-auth/sre-cluster-role.yaml

Without this change either `dev` or `sre` roles would have `viewer`
access but not both.

Fix name collision for ClusterRoleBinding

---

charts/gsp-cluster/templates/02-gsp-system/pipeline-operator.yaml

This keeps getting OOMKilled, even though there's plenty of space on
the node.  I've also seen its working set grow above 30Mb in the
metrics.  So I think we should bump the limit upwards.

bump pipeline-operator resource limits

---

pipelines/deployer/deployer.yaml

it's an oxymoron i know
I got confused by these lines - the release only has one file which
fits each of these wildcards - `source.tar.gz.asc` and `source.tar.gz`
respectively.  I found it confusing that these were wildcards because
it looks like it's trying to validate many signatures and unpack many
tarballs (and there are other tarballs in the release, only with `tgz`
in the name instead of `tar.gz`).
I think it's much clearer to use the literal filenames instead of a
wildcard.

make bash clearer

---

charts/gsp-cluster/values.yaml

Postgres has run out of disk space in sandbox.  The default is 8Gi.
I have other questions about this postgres - eg, it's run as a
ReplicaSet not a StatefulSet.  But for the moment, let's bump the disk
to fix sandbox and stave off problems in verify.

bump concourse postgres size

---

charts/gsp-cluster/values.yaml

Reverts alphagov/gsp#311
This failed with an error that included the text
```
for: "manifests/gsp-cluster/charts/concourse/charts/postgresql/templates/pvc.yaml": persistentvolumeclaims "gsp-postgresql" is forbidden: only dynamically provisioned pvc can be resized and the storageclass that provisions the pvc must support resize
```
😒 
So postgres is still broken but it's not clear how to resize it. Reverting to at least get back to as-broken-as-before.

Revert "bump concourse postgres size"

---

pipelines/release/release.yaml

Create a draft release until all the files have been signed and are ready for uploading & publishing to avoid the race condition currently inherent in the gsp release pipeline.
* The `put` for a release (or `pre-release`, or whatever) is "atomic" in the sense that the release isn't published (in a way that another `github-release` resource would `check` it) until all the files are uploaded
* github releases & tags follow the same logic as the resource; specifically: `draft XOR (pre-release OR release)` such that if a `pre-release` is `put` that matches a `draft` release with the same tag the draft disappears
* If a publish fails (or if some of the builds fail but others succeed) we'll fall foul of concourse's odd caching. Specifically, the version is bumped based on the previous …

Create draft releases until everything is signed.

---

charts/gsp-cluster/templates/00-aws-auth/default-storage-class.yaml

By default dynamic scaling is not enabled. But in EKS (which is EBS-backed) persistent volumes can be scaled.

Allow the default storage class to support dynamic scaling of volumes.

---

charts/gsp-cluster/values.yaml

Reverts alphagov/gsp#312
The storage class has been updated to support dynamic resizing now. This might now work.

Revert "Revert "bump concourse postgres size""

---

components/concourse-operator/pkg/controller/pipeline/pipeline_controller_test.go

Fix typo in concourse-operator

---

pipelines/deployer/deployer.tf

The VPC endpoint for connecting with CloudFundamental needs some values
out of this cluster state. This exposes them.

Expose necessary outputs for VPC endpoint consumption.

---

CODEOWNERS

- Right now, we have nothing apart from the GitHub bot for Slack posting
in the #re-gsp channel. This way, we can disable that integration and
get less "immediate-attention" Slack spam.
- These review requests will appear in team members' Review Requested
list (https://github.com/pulls/review-requested), and they'll get
email about them.
- As with some other repos that use this pattern, the repo requires two
reviews so reviewers do have to do a manual step of "re-requesting a
review from the teams(s)", but that's a two second thing.

Add a CODEOWNERS file to automatically request reviews from teams

---

pipelines/deployer/deployer.defaults.yaml

Upgrade EKS control-plane to kubernetes v1.13
It is important to stay up to date.
[AWS Container Roadmap](https://github.com/aws/containers-roadmap/projects/1)
- [EKS Support for Kubernetes 1.13](https://github.com/aws/containers-roadmap/projects/1#card-16594285) SHIPPED
- [Kubernetes v1.10 Deprecation (July 22, 2019)](https://github.com/aws/containers-roadmap/projects/1#card-21819192) COMING SOON
Please merge these first:
* https://github.com/alphagov/verify-cluster-config/pull/8
* https://github.com/alphagov/tech-ops-cluster-config/pull/217

Upgrade control-plane to v1.13.x

---

components/service-operator/apis/database/v1beta1/postgres_types.go
components/service-operator/apis/database/v1beta1/postgres_types_test.go
components/service-operator/apis/storage/v1beta1/s3_types.go
components/service-operator/apis/storage/v1beta1/s3_types_test.go

Turns out exportTo in a ServiceEntry spec is a list of strings, not a string.
Fixes #657.

svcop: Fix ServiceEntry creation/update

---

charts/gsp-cluster/charts/gsp-monitoring/values.yaml

we have seen prometheus use up all the disk space as it tries to keep
metrics for 60d retension ... but the disk is only 50GiB ... to limit
prometheus to less than the available disk space we set retentionSize

limit retention size lower than prom disk size

---

charts/gsp-cluster/charts/gsp-monitoring/values.yaml

This flag enables compression of the write-ahead log (WAL). Depending on
your data, you can expect the WAL size to be halved with little extra
cpu load.

enable compression for prometheus wal

---

pipelines/deployer/deployer.yaml

5m is too close to the build-deploy loop ... give it a bit more time

allow 10m for check-canary

---

charts/gsp-cluster/values.yaml

use the btrfs driver for concourse's baggageclaim storage in the hope
that it avoids the issues we seem to be increasingly observing where
where workers stall with errors like
"baggageclaim.failed-to-set-up-driver".
It's possible the recent change from EBS persistantvolumes to local emptydir volumes is not playing nicely with the overlay driver but to be honest this is a bit of an experiment to see if the situation improves.... there is a similar [thread here](https://discuss.concourse-ci.org/t/overlay-driver-failed-to-set-up-driver-on-5-4-1-5-5-0/1737) and [issue here](https://github.com/helm/charts/issues/5355) describing similar symptoms that are resolved by switching to either `naive` or `btrfs` drivers

switch bagageclaim to use buttahheffess

---

charts/gsp-cluster/dashboards/concourse.json

after switching concourse workers to use node storage (via emptyDir) the
grafana dashboard was big lie since it was attempting to chart storage
of the old persistant volume claim ... this changes it to display the
node's own remaining storage, which should be the same of the worker's
available storage since we do not limit the emptyDir in any way.

show ci node avail storage not old pvc

---

components/concourse-operator/README.md

Following #675/#693 we introduced another place where we get
concourse-operator-source - which would be fine except the last commit to that
component was in #571 which was approved by Andy, who left and is no longer on
the list of people trusted to approve.

Add random newline to concourse-operator source

---

charts/gsp-cluster/charts/gsp-monitoring/values.yaml

we need at least 100GB for 60 days of retention and would like some
spare room for the WAL log and compression to take place.

resize prometheus PV to 200GiB

---

components/service-operator/apis/database/v1beta1/postgres_types.go
components/service-operator/apis/database/v1beta1/postgres_types_test.go
components/service-operator/apis/storage/v1beta1/s3_types.go
components/service-operator/apis/storage/v1beta1/s3_types_test.go
components/service-operator/controllers/postgres_cloudformation_test.go
components/service-operator/controllers/s3_cloudformation_test.go
components/service-operator/internal/aws/cloudformation/controller.go
components/service-operator/internal/aws/cloudformation/types.go

Alter the interface for ServiceEntryCreator to allow returning multiple ServiceEntry specs
It's not possible to set multiple hosts for a TCP ServiceEntry with DNS
resolution, so we need to be able to return multiple service entry
specs from a ServiceEntryCreator in order to satisfy the requirements of
services like RDS that can have multiple endpoints.
This should resolve the issue with the current implementation that relies on SNI headers (TLS) that not all postgres clients appear to send.

allow returning multiple ServiceEntries from ServiceEntryCreators

---

charts/gsp-cluster/templates/00-aws-auth/kube-proxy.yaml

Currently prometheus is reporting that all kube-proxy instances are down.
Hopefully this fixes it.

Expose kube-proxy metrics.

---

charts/gsp-cluster/templates/00-aws-auth/kube-proxy-config.yaml
charts/gsp-cluster/templates/00-aws-auth/kube-proxy.yaml

Kube-proxy appears to favour the config file value over the command line argument. So we're going to use that instead.

Expose kube-proxy metrics

---

pipelines/README.md
pipelines/examples/clusters/sandbox.yaml

* Fix set-deployer-pipeline README to not set unused environment variable - this is only used in set-release-pipeline.
* Set EKS version in the example config to the one we actually use.
* Add Google client dummy secrets to the example config.
* Enable NLB in the example config.

Various fixes for new clusters

---

modules/gsp-cluster/main.tf
modules/gsp-cluster/variables.tf
modules/gsp-network/outputs.tf
modules/k8s-cluster/main.tf
modules/k8s-cluster/variables.tf
pipelines/deployer/deployer.tf

We are currently running into the following Terraform bug when trying to apply
a new cluster using Terraform 0.11:
https://github.com/hashicorp/terraform/issues/12570#issuecomment-309995500
This is because we are trying to run `length()` on a thing that references
another module which has not yet been applied.
We know what the length of it is already, so we can just output the
pre-calculated value.

Fix Terraform plan for a new cluster

---

modules/gsp-cluster/service-operator.tf

* Fix DB subnet group name to not hardcode sandbox
* Fix RDS from worker security group to name by cluster

svcop: Fix RDS terraformed things to not break multi-cluster accounts

---

modules/gsp-cluster/nlb.tf
modules/gsp-network/outputs.tf

Our plan is showing `module.gsp-cluster.aws_lb.ingress-nlb[0] will be destroyed`
So maybe Terraform is now mishandling our count stuff. Trying with brackets.
Meanwhile, it's complaining about making a map with keys by expression, so
revert that back to using string interpolation for the keys.

Try to fix problems relating to terraform 0.12

---

Brewfile

- We no longer need the "cask" tap, or the "OS.linux?" conditional to
pull a different formula.
**This will need pulling and re-signing as I'm no longer a trusted
dev.**

Brewfile: `minikube` is a standard Homebrew formula now

---

pipelines/deployer/deployer.yaml

After https://github.com/alphagov/gsp/pull/719 gets merged, we'll probably be
fine with the minor (potentially nil?) changes it wants to make now in sandbox.
Do we want to check it in verify/portfolio too, i.e. promote that to verify to see
the plan before merging this?

Actually apply the terraform upgrade

---

modules/gsp-cluster/service-operator.tf

It turns out renaming DB Subnet Groups, as this was going to do in Verify,
results in the replacement of the attached RDS Clusters.

Partially revert #706 to get Terraform apply working

---

charts/gsp-cluster/values.yaml
modules/k8s-cluster/main.tf

Increase node volum storage to 75Gi and limit the empty volume (instance storage) concourse workers are using
for there ephemeral storage to 60Gi so that they don't fill up the
node's disk.
We believe this being unlimited to be a source of previous disk-pressure
and ultimate responsible for the scheduler eviciting important pods
(like CNIs and kube-proxy) to releave that pressure.
The number 60Gi was chosen as as we are setting the node storage to 75Gi and want to leave a decent chunk for the OS and other pods to avoid disk-pressure issues.

limit concourse worker's disk volume to 60Gi

---

charts/gsp-cluster/templates/04-main-team-pipelines/cd-smoke-test-pipeline.yaml
docs/gds-supported-platform/making-things-private-in-harbor.md

We want to be able to remove the client IP safelist. We've decided to do
this by removing the need to have an ingress for the API entirely. This
change will mean that Concourse will use the internal service for the
Harbor API because the `concourse-harbor-resource` will use it by
default.

Use the internal service to access Harbor API

---

docs/architecture/adr/ADR040-cluster-stability-node-replacement.md
docs/architecture/adr/README.md

To try to improve platform reliability during platform change operations.
As an SRE I sometimes need to change AMI (for an EKS update), instance type, or
anything else in the launch template in some way (e.g. instance role), and
doing this results in the replacement of all nodes.
In addition sometimes this may be triggered by AWS releasing a new AMI for our
EKS version.
This breaks a lot right now and we should fix that.

ADR040: Safe replacement of nodes

---

charts/gsp-cluster/templates/01-aws-system/aws-ssm-agent-daemonset.yaml
components/concourse-task-toolbox/bin/determine-platform-version.py
pipelines/release/release.yaml

Me and Chris noticed this while doing #713
The only other thing in the components directory which is not build by our
release pipeline (or the cd-smoke-test) is the cloudhsm-client-test which is
only a testing thing for us.

Build AWS SSM Agent in release pipeline too

---

charts/gsp-cluster/values.yaml

fluentd-cloudwatch pods are gsp-critical, they have a KIAM annotation. So KIAM
should be as well.

Make KIAM Server and Agent pods gsp-critical

---

templates/managed-namespaces-gateways.yaml

sets the managed namespace loadbalaners to use the "cluster" mode (the
default mode). In this mode, loadbalancers will include all node in
there target groups and will rely on the inter-cluster networking to
route traffic to the correct pod, instead of directly targeting the node
where pod is currently located. This looks less effcient, but is less
sensitive to node failure.
we previously used externalTrafficPolicy: Local as we believed we had a
need to preserve client ip addrs to perform whitelisting tasks.
we have since discovered that we can relax this need and have removed
our use of ip whitelisting of resources from the system.
we suspect having the ingress loadbalancer service in
`externalTrafficPolicy: Local` mode has contributed to problems we have
seen during node rollouts …

use externalTrafficPolicy: Cluster for ingress LBs

---

modules/gsp-cluster/monitoring-system.tf
modules/gsp-cluster/splunk-system.tf

This change adds three new log group names and configures Lambda Splunk Forwarder to start forwarding these log groups to Splunk.
1. /aws/containerinsights/Cluster_Name/application: it contains all log files in /var/log/containers
2. /aws/containerinsights/Cluster_Name/host: it contains logs from /var/log/dmesg, /var/log/secure, and /var/log/messages
3. /aws/containerinsights/Cluster_Name/dataplane: it contains logs in /var/log/journal for kubelet.service, kubeproxy.service, and docker.service. Please note that kubeproxy is running in pod and will appear in the application group.
AWS CloudWatch documentation (https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/Container-Insights-setup-logs.html) uses these three log group names.
Author: @adityapahuja

AUT70: Add 3 new log group names

---

charts/gsp-cluster/charts/gsp-monitoring/templates/rules-general.yaml

This deletes the KubeletTooManyPods alert.  The alert was useful back
before we had the cluster autoscaler and would need to consider
manually scaling if the cluster was getting too full.  But now we have
the autoscaler this alert is just causing noise in the slack channel.

fix: delete KubeletTooManyPods alert

---

modules/gsp-cluster/monitoring-system.tf

This change allows cloudwatch_log_shipping_role to have access to the following three new resources.
1. application_logs
2. dataplane_logs
2. host_logs
Author: @adityapahuja

AUT70: Add missing resources to cloudwatch_log_shipping_policy

---

charts/gsp-cluster/charts/gsp-monitoring/templates/rules-kubernetes-system.yaml

This alert, last touched in f1ef6a3d2d8c2a2fb0b001b22a7fb89489837844,
was firing.  This was because some components have a `minor` label of
`14` and some have `14+` so the alert treats these as two different
versions of kubernetes.
This partly reverts f1ef6a3d2d8c2a2fb0b001b22a7fb89489837844 back to
the regex way of doing things, but edits the regex to only look at the
first two components of the `gitVersion` label (ie 1.14, not 1.14.6).
This should silence the currently firing KubeVersionMismatch alerts.

fix: quench KubeVersionMismatch alert

---

charts/gsp-cluster/charts/gsp-monitoring/templates/rules-kubernetes-system.yaml

The  "prometheusrules" is invalid: : group "kubernetes-system", rule 1,
"KubeVersionMismatch": could not parse expression: parse error at char 123:
unclosed left parenthesis

Fix syntax of KubeVersionMismatch rule

---

charts/gsp-cluster/templates/02-gsp-system/harbor-virtual-service.yaml

We don't require access to the portal at all. We reference the internal
harbor API service when we require API access. We only require API
access from within the cluster.

Remove public access to the Habor API/Portal

---

docs/architecture/adr/ADR042-static-ingress-ip-workaround.md

Details on why we are using AWS Global Acelerator pointing at ingress
NLBs.
tl;dr... it's a bit of a clickops hack while we wait for EKS to support
EIP allocations on NLBs in v1.16

ADR042: static ip workaround for public ingress

---

modules/gsp-user/iam.tf

Currently, we tag our NLBs to make it clear which
namespace/service/whatever they belong to.  However
ordinary (non-full-IAM-admin) users don't have permission to see these
tags.  Confusingly, if you don't have
`elasticloadbalancing:DescribeTags` permissions, the AWS Console will
tell you that the loadbalancer doesn't have any tags, not that you
don't have permission to see the tags.
Also confusingly, ViewOnlyAccess doesn't give permission to see load
balancer tags, even though it gives permission to see all sorts of
other tags.
Attaching the ElasticLoadBalancingReadOnly managed policy is
sufficient to allow users to see NLB tags.  I have tested this in
sandbox using admin powers on my non-admin user :snowflake:

Allow all users to see NLB tags

---

charts/gsp-cluster/templates/02-gsp-system/harbor-virtual-service.yaml

This should remove routes that are not essential to regular Docker registry interactions (for example `docker pull/push`).
This might work, or might not work. This time round I'll actually do a bit more checking to see that sandbox is actually working before promoting.

Remove non-essential, non-registry related Harbor routes

---

pipelines/deployer/deployer.yaml

We are just blocking the things we were concerned about being open
entirely therefore removing the need for the safelist.
This cleans up the resources that have been removed as part of a
previous PR[1].
This can be reverted once it's deployed everywhere.
[1] https://github.com/alphagov/gsp/pull/746

Cleanup old client IP safelisting stuff

---

charts/gsp-cluster/templates/03-namespaces/namespace.yaml
charts/gsp-cluster/templates/04-main-team-pipelines/cd-smoke-test-pipeline.yaml
charts/gsp-cluster/values.yaml
pipelines/deployer/deployer.yaml

* Use our github-resource (albeit in a configuration that doesn't fully test it) in the cd-smoke-test pipeline
* Make use of the `((trusted-developers.github-accounts))` and `((github.api-token))` secrets to ensure their existance
* Pull the canary source from the `((cluster.release))` that the cluster was deployed from instead of `master` so it is in sync with the deployment
* So that changes to the canary are not rolled out to clusters that are not ready for the new changes yet
* So that we at least know that the github-resource work as we are not testing it anywhere else
* So that we know that the secrets (which we tell service teams to use in their pipelines) actually exist
Closes #214

ensure canary deploys from a trusted release

---

charts/gsp-cluster/templates/00-aws-auth/managed-namespaces.yaml

Feels like this should be replaced by a `additionalNamespaceLabels` cluster-config construct. But that's a bigger change than the scope of this story.

Allow configured namespaces to connect to the PSN.

---

modules/gsp-cluster/data/values.yaml

allow everyone to edit dashboards in grafana.
even though we do not persist grafana configuration (prefuring to setup
dashboards declaratively) it is still useful to be able to click around
and make changes in the UI to test out dashboard changes.
the viewers_can_edit permisisons only gets us so far, but is missing
some key editing features like "creating a dashboard"
:information_source: not actually sure this will work for oauth users, or maybe it will only work for "new" oauth users, so might want to give grafana pod a kick to clear out it's state if this doesn't have an immediate effect.

make everyone an Editor in grafana org=1

---

docs/architecture/adr/ADR042-static-ingress-ip-workaround.md
docs/architecture/notes/global-accelerator-spike.md

it may be a while before we get to deprecate our use of the global
accelerator, but we may want to refer back to the spike notes.

store global-accel spike notes for future

---

pipelines/release/release.yaml

uploading /tmp/build/put/deployer-package/pipelines
error running command: the asset to upload can't be a directory

Follow-up #761: Fix release pipeline by uploading pipeline directory

---

pipelines/deployer/deployer.yaml

Getting no log entries would cause LASTSEENLOG to be an empty string instead of
an integer, which Bash then tried to compare with LOGS_SINCE and errored out.

check-tools job: Don't fail without retrying if we get no log entries

---

pipelines/deployer/deployer.yaml

If curl fails we don't want it going `/bin/bash: line 5: [: : integer expression expected`

Avoid bash syntax error in check-canary, add pipefail

---

pipelines/deployer/deployer.yaml

This fails in sandbox sometimes, probably Prometheus is not ready yet.

check-tools: Retry a few times rather than just fail

---

pipelines/deployer/deployer.yaml

we recently changed the name of the log group where contianer logs get
shipped to in cloudwatch, as well as adding some additional log shipping
for things running on the worker node's themselves.
this updates the check-logging test in the pipeline to watch for logs
arriving in all of these groups.

ensure all loggroups recv traffic in check-logging

---

pipelines/deployer/deployer.yaml

the eks logs arrive fast, and the acuracy of the timestamp is not enough
causing the test to fail as there are logs since exactly the time
requested.

resolve check-logging flakes for fast loggroups

---

pipelines/deployer/deployer.yaml
pipelines/release/release.yaml

build the lifecycle hook lambda binary, zip it up and store it in s3
(for use elsewhere in release pipelin) then package it up along with the
main gsp release (for consumption by public/deployer pipelines)
updates the deployer pipelines to consume the released zip when the
resource type is set to release.

build and package aws-node-lifecycle-hook release

---

pipelines/deployer/deployer.tf

We get requests for this information a lot. So it makes sense to print
them out during the deployment pipeline for easy reference.

Expose the ingress and egress IPs in the terraform output.

---

pipelines/deployer/deployer.yaml
pipelines/release/release.yaml

we have removed the gpg keys requirements, so no longer require that
selfupdate adds the secrets for the keys to the pipeline during
selfupdate

remove redundent keys.vars.yaml from selfupdate

---

pipelines/release/release.yaml

The deployer pipeline copies this to the expected location, and this was the
old path anyway.

Fix path that aws-node-lifecycle-hook binary gets zipped to in release

---

components/aws-node-lifecycle-hook/go.mod
components/aws-node-lifecycle-hook/go.sum

See https://github.com/dominikh/go-tools/issues/658
The upstream for this module is borked, but we can go direct to github

fix(node-lifecycle-hook): fix broken upstream for honnef.co

---

modules/gsp-cluster/splunk-system.tf
modules/gsp-cluster/variables.tf
pipelines/deployer/deployer.defaults.yaml
pipelines/deployer/deployer.tf
pipelines/deployer/deployer.yaml
pipelines/examples/clusters/sandbox.yaml

Destination to be enabled on a per-cluster basis (so we can start off with
sandbox and see how things look), and the destination ARN will come from a Big
Concourse secret, due to containing the CLS account ID.

Add CLS integration support

---

pipelines/release/release.yaml

That changed not only the place it was putting the file inside the zip but also
the place it looks for the file.

Follow-up #799: Fix aws-node-lifecycle-hook release

---

components/service-operator/Dockerfile
components/service-operator/go.mod
components/service-operator/go.sum

This sets the GOPROXY environment variable to the default version in
go 1.13.  This means we fetch modules from the golang.org go proxy,
rather than direct.  This would have avoided the issues we saw with
honnef.co the other day (so I have reverted that change).  I also
think that it may make the build faster on concourse; it's worth a go.
In any case, when we upgrade to go 1.13, this will be the default
setting so we might as well try it out now.

build(svcop): use GOPROXY to fetch go modules

---

charts/gsp-cluster/templates/00-aws-auth/kube-system-namespace.yaml

If a node is removed that carries the only running instance of a webhook
target without a notification to the apiserver the control-plane
effectively breaks because the webhook is called as part of controller-
manager calls into the apiserver. Excluding the kube control-plane from
such checks allows the cluster to continue to function.

Add control-plane label to kube-system.

---

components/service-operator/controllers/postgres_cloudformation_test.go
components/service-operator/controllers/suite_test.go
components/service-operator/internal/aws/sdk/sdkfakes/fake_client_happy.go

And use it in RDS to ensure we get a hostname we can resolve.

svcop: Permit overriding dummy cloudformation outputs in tests

---

components/service-operator/apis/queue/v1beta1/sqs_types_test.go
components/service-operator/controllers/sqs_cloudformation_test.go
docs/gds-supported-platform/gsp-service-operator.md

also add the output to a few places we were listing the ordinary queue URL

svcop: document dead-letter queue support

---

modules/k8s-cluster/main.tf

It doesn't like this syntax:
The given key does not identify an element in this collection value.

Follow-up #812: Fix terraform

---

components/service-operator/apis/storage/v1beta1/s3_types.go
components/service-operator/apis/storage/v1beta1/s3_types_test.go
components/service-operator/controllers/s3_cloudformation_test.go
components/service-operator/controllers/suite_test.go

ensure that istio knows about the global s3 endpoint for any svc-op
provisioned s3 buckets.
sometimes the sdk talks to the regional s3 endpoint
(xxx.s3.eu-west-2.amazonaws.com) and sometimes it talks to the global s3
endpoint (xxx.s3.amazonaws.com) this means we should create
ServiceEntries for both.
also make the region a little less hard-coded, by doing some of the work to read it from outputs

add ServiceEntry for s3 global endpoint too

---

modules/gsp-cluster/values.tf

I had one generated starting with a close curly bracket `}`, this lead to an
error like:
Error: failed to parse cluster-values/values.yaml: error converting YAML to
JSON: yaml: line 169: did not find expected node content

Encode Grafana admin password as it can contain special characters

---

charts/gsp-istio/values.yaml

drop the percentage of traffic sent to jaeger/tracing from 100% down to
5%.
The "out of the box" jaeger bundled with istio is struggling in
production deployments to handle 100% sampling rate, the istio-tracing
workloads end up using 10GB+ of ram and stealing alot of the node's CPU.
We don't currently rely heavily on the tracing ui/visualizations that
jaeger bring to the table so we are happy dropping the sample rate
significantly.
If in the future we want to take advantage of sampling every single
request, then we should consider using the [jaeger operator](https://github.com/jaegertracing/jaeger-operator) to deploy a
more production-grade scalable deployment, since the istio-bundled one is
really just ment to get you started.

Reduce traffic sampling sent to jaeger to 5%

---

components/canary/chart/templates/prometheus-rules.yaml

we only route alerts to the re-autom8-alerts channel that have a "layer"
label present... so this adds a suitable label of "cicd" to denote that
this alert is related to the continuous delivery system and to ensure it
gets piped to the channel.
https://github.com/alphagov/prometheus-aws-configuration-beta/pull/354

add layer:cicd label to canary alert

---

pipelines/deployer/deployer.yaml

This change has been deployed out and can be removed now.

Remove the temporary removal of gatekeeper sync resource

---

templates/managed-namespaces-gateways.yaml

fix the number of ingressgateways replicas to 3 instances and disable the
HPA (HorizontalPodAutoscaler) for all managed-namespaces.
We have evidence that connections are getting dropped when the
ingressgateways are scaled-in, and are seeing the HPA agressively scale
in/out the ingressgateways (possibly due to the low-traffic they
encounter).
We intend to fix the ingressgateways at 3 replicas for now and monitor the
situation, if we stop seeing the check-canary failures after this point,
then this will be strong evidence that the HPA of the ingressgateways
with low-traffic was the source of the issues and we can revisit how/if
we should/could re-enable autoscaling to maintain the cost benefits it
brings.

disable autoscaling of ingressgateways

---

templates/managed-namespaces-gateways.yaml

fix the number of ingressgateways replicas to 3 instances and
(effectivly) disable the HPA (HorizontalPodAutoscaler) for all
managed-namespaces.
We believe that connections are sometimes getting dropped when the
ingressgateways are scaled-in, and are seeing the HPA agressively scale
in/out the ingressgateways (possibly due to the low-traffic they
encounter).
We intend to fix the ingressgateways at 3 replicas and monitor the
situation, if we stop seeing the check-canary failures after this point,
then this will be strong evidence that the HPA of the ingressgateways
with low-traffic was the source of the issues and we can revisit how/if
we should/could re-enable autoscaling to maintain the cost benefits it
brings.

hardcode autoscaling of ingressgateways to 3x

---

pipelines/deployer/deployer.yaml

we often see the check-logging jobs fail to retry correctly.
without looking too deeply at the job the likely culprits are (1) the
retry logic is not quite right and (2) 'jq | head' is a known pipefail
scenario.
so as an attempt at a quick fix for the flakey test, (1) use concourse
'attempts' to retry instead of a bash loop and (2) drop the error on
pipefail option and live on the stream-redirecting-edge

use attempts to retry check-logging tasks

---

pipelines/deployer/deployer.yaml

... on every single deploy.
Ultimately maybe we move to the release pipeline deploying everything but for
now this component is the odd one out.

On-demand clusters: Get node lifecycle hook from S3 instead of re-building

---

pipelines/deployer/deployer.yaml

We don't want anything left around costing money that isn't being managed by
a cluster. Also if you leave e.g. Postgres stuff lying around, terraform destroy can
fail due to trying to remove stuff like DB Subnet Groups and Security Groups that
are still in use.

Delete svcop resources on cluster destroy

---

modules/gsp-cluster/harbor.tf
modules/gsp-cluster/values.tf

Also, while we're here, set special to false so we stop running the risk of
getting syntax errors while handling these and inadvertently exposing them in
logs.

Replace random_string with random_password for concourse password

---

pipelines/deployer/deployer.yaml

Several contributing factors:
- ASG scale-down goes in 5 minute steps (so if one AZ has 6 nodes that's
30 minutes)
- deleting AWS resources such as RDS can take significant time (~12 mins)
- predicting how long a sensible timeout would be is nearly impossible for
a dynamic payload
- the "deploy" step has no timeout

Remove timeout for drain step in cluster destroy.

---

modules/gsp-cluster/main.tf
modules/gsp-cluster/variables.tf
modules/k8s-cluster/data/nodegroup-v2.yaml
modules/k8s-cluster/main.tf
modules/k8s-cluster/variables.tf
pipelines/deployer/deployer.tf
pipelines/deployer/deployer.yaml

We want these to be managed by the cluster autoscaler, not Terraform.

Override Terraform desired worker counts in existing clusters with current values

---

modules/lambda_splunk_forwarder/lambda.tf

I built the ZIP in #847 from a Debian Buster VM instead of something else like
Ubuntu Bionic, and the default version of Python 3 was 3.7 rather than 3.6.
This should be fine. However it does seem to mean we need to bump the version
of python used to run the lambda.
Alternatively I could make the ZIP again using a distro with Python 3.6 by
default, or attempt to get Python 3.6 on Debian Buster and make the ZIP
build process use that.

Set log forwarding runtime to python3.7

---

charts/gsp-cluster/templates/04-main-team-pipelines/cd-smoke-test-pipeline.yaml

the serial-group, preventing the "build" and "deploy" jobs of the
cd-smoke-test pipeline running at the same time, was added to work
around the notary-only-signs-latest-tag bug. This bug is no longer a
factor as we are not signing the images with notary, so it's fine to
deploy old versions of images and we can safely remove the serial group.

remove cd-smoke-test serial group

---

pipelines/deployer/deployer.yaml

We don't use Helm properly, so our deletion hook for these jobs didn't take
effect. This should do the trick.

Temporary tidyup for prometheus-operator

---

docs/gds-supported-platform/bootstrapping-clusters.md

**Why**
Error: Error creating Cloudwatch log subscription filter: ResourceNotFoundException: The specified log group does not exist.
status code: 400, request id: ae870fb7-36e4-4835-bfcf-fe601a3068a7
**What**
Add advice to documentation to disable Splunk and show how to.

add advice on disabling splunk for on-demand clusters

---

charts/gsp-cluster/templates/03-namespaces/namespace.yaml

In a future PR we need to be able to delete these without having to
reference the individual namespaces themselves. Collective labels allow us
to do that.

Add collective labels to namespace-scoped resources.

---

modules/k8s-cluster/data/nodegroup-v2.yaml

We currently wait 5 minutes after terminating and launching an
instance in the worker node group ASG.
We now have lifecycle hooks to ensure we are confident that terminated
instances have successfully evicted their pods onto other nodes.
I think we could *possibly* get rid of PauseTime entirely, but this is
a more conservative proposal for now.

reduce time waiting between node launches to 2 minutes

---

docs/gds-supported-platform/bootstrapping-clusters.md

**What**
Add note about need to be admin.
Change base64 -D into --decode.
**Why**
In discussion with @samcrang, user needs to be 'admin' rather than 'sre' in order to access the required secrets mentioned in the doc.
Also discussed with Sam, the gnubin base64 requires -d rather than -D, so altering that to --decode for compatibility between these versions.

add a note about being admin and change -D into --decode for operability

---

docs/gds-supported-platform/bootstrapping-clusters.md
modules/gsp-cluster/harbor.tf
modules/gsp-cluster/variables.tf
pipelines/deployer/deployer.defaults.yaml
pipelines/deployer/deployer.tf
pipelines/deployer/deployer.yaml

When using on-demand clusters there's not much need to take a snapshot
when destroying the Harbor RDS cluster.
Without this change a snapshot hangs around after the cluster has gone
and stops destroys from working correctly if an on-demand cluster with
the same name is created later.

Allow final RDS snapshot to be disabled

---

pipelines/deployer/deployer.yaml

Without this change the termination lifecycle hook Lambda hangs until it
timesout as it tries to drain nodes that fail to evict pods because it
would cause a violation to pod disruption budgets.
Whilst this is sensible most of the time (for example when rolling
nodes) it's not required when destroying a cluster entirely and actually
prevents them being destroyed without intervention.

Delete PodDisruptionBudgets when destroying cluster

---

modules/gsp-cluster/harbor.tf

We are currently using `rds-ca-2015`. This root CA will expire soon and
a new root CA has been provided by AWS:
```
The current CA expires on March 5, 2020, requiring updates to client
applications and database instances that have certificates referencing
the current CA. Client applications must add new CA certificates (root
and intermediate where necessary) to their trust stores, and RDS
database instances must separately use new server certificates before
this hard expiration date. However, we strongly recommend you complete
these changes before February 5, 2020. After February 5, 2020, we will
begin scheduling certificate rotations for your RDS database instances
prior to the March 5, 2020 deadline. The automatic update(s) will be
scheduled within your maintenance window.
```
This …

Explicitly set harbor rds root ca

---

modules/gsp-cluster/harbor.tf

Merge #868 first.
```
To protect your communications with RDS database instances, a CA
generates time-bound certificates that are checked by your client
applications that connect via SSL/TLS to authenticate RDS databases
before exchanging information. AWS renews the CA and creates new root
certificates every five years to ensure RDS customer connections are
properly protected for years to come.
```

Use latest rds root ca

---

pipelines/deployer/deployer.yaml

Successfully tested using an on-demand cluster.

Apply cluster resources from config repository

---

modules/gsp-cluster/data/values.yaml

https://docs.aws.amazon.com/eks/latest/userguide/iam-roles-for-service-accounts-technical-overview.html#service-account-configuration

Fix Grafana IAM role: Annotate ServiceAccount, not Pods

---

charts/gsp-cluster/templates/00-aws-auth/auditor-cluster-role.yaml

The API Group for the concourse resources was recently updated to get it
off the "reserved" group suffix of 'k8s.io'. The new roles and permissions
work was done before this migration happened. This change brings the roles
in line.

Update apigroup for concourse operator resources.

---

modules/k8s-cluster/main.tf

the thumbprint identifies the root CA for the OIDC provider. See
https://docs.aws.amazon.com/IAM/latest/UserGuide/id_roles_providers_create_oidc_verify-thumbprint.html
in this case, this thumbprint is the thumbprint of the root CA
presented by `oidc.eks.eu-west-2.amazonaws.com`; this isn't likely to change
I checked and the same thumbprint applies to eu-west-1
This is required for IAM Roles for k8s service accounts to work.  If
you don't have this, you get an error similar to the following:
```
aws sts get-caller-identity
An error occurred (InvalidIdentityToken) when calling the AssumeRoleWithWebIdentity operation: OpenIDConnect provider's HTTPS certificate doesn't match configured thumbprint
```

Set CA thumbprint for IAM OIDC provider

---

modules/gsp-cluster/data/values.yaml
modules/gsp-cluster/grafana.tf

This reverts commit 21aab2202f57de90641f6a38dba09df42e025a99.
This reverts commit cd36603e6d7f382e84eec57d7bc41908141d2fdd.
It turns out that Grafana overrides the default credential provider chain, and so we can't use this right now. https://github.com/grafana/grafana/issues/20473

Revert Grafana to use KIAM to deal with IAM roles

---

modules/gsp-cluster/concourse.tf
modules/gsp-cluster/data/values.yaml
modules/gsp-cluster/kiam-system.tf
modules/gsp-cluster/values.tf

What good is a role without policies?
This used to have CodeCommit stuff attached, until https://github.com/alphagov/gsp/pull/171

Remove IAM role for Concourse workers without any policies attached

---

charts/gsp-cluster/templates/03-namespaces/external-dns.yaml

So it uses a new enough version of the AWS SDK to support IAM roles for EKS.
Also includes some additional security rules that've been added to the chart
since our fork. We can probably get away without them.
I think we forked off chart version 2.5.1 or later before, this will be
equivalent to 2.14.3.
Likely conflicts with #857

Update external-dns from 0.5.15 to 0.5.18

---

components/service-operator/Dockerfile

I tried specifying GOPROXY in #806 but it didn't speed up the builds.
I think there were two problems:
1. setting GOPROXY after running `go mod download` won't
help. :facepalm:
2. go 1.12 doesn't support a comma-separated list in the GOPROXY env
var, you have to specify a single URL
This hopefully fixes those issues and maybe will finally speed up the
svcop build?

Try speeding up svcop build with GOPROXY again

---

templates/managed-namespaces-gateways.yaml

We are causing alert noise in tenant namespace with KubeHpaMaxedOut
alerts.  This is because ingressgateways have a HPA with min = max =
3.
This commit sets `autoscaleEnabled: false` which will remove the HPA
kubeyaml.  We might need to go and manually remove the HPA objects
afterwards.
We already set `replicaCount: 3` so the Deployment should have the
correct number of replicas without `autoscaleEnabled: true`.

Remove ingressgateway HorizontalPodAutoscaler

---

modules/gsp-cluster/cert-manager.tf
modules/gsp-cluster/data/values.yaml
modules/gsp-cluster/values.tf

**Why**
To gain the simplicity advantage of EKS service accounts.
**What**
Alter cert-manager role to use IAM roles for EKS service accounts.
With Alex Monk @Krenair

switch cert-manager role to use IAM roles for EKS service accounts

---

pipelines/deployer/deployer.yaml

The concourse output for applying user-state has the warning:
Warning: Value for undeclared variable
(...)
The root module does not declare a variable named "cluster_number". To use
this value, add a "variable" block to the configuration.
This commit is a simple fix for that problem :)

remove unused variable `cluster_number` from users tf

---

charts/gsp-cluster/values.yaml

cert-manager runs as a non-root user, which means that it can't access
the volume containing the EKS token used to authenticate as an IAM
Role.
There is an [issue on cert-manager][1] which suggests using `fsGroup`.
From the k8s docs fsGroup is:
> A special supplemental group that applies to all containers in a
> pod. Some volume types allow the Kubelet to change the ownership of
> that volume to be owned by the pod: 1. The owning GID will be the
> FSGroup 2. The setgid bit is set (new files created in the volume
> will be owned by FSGroup) 3. The permission bits are OR'd with
> rw-rw---- If unset, the Kubelet will not modify the ownership and
> permissions of any volume.
I guess this basically means that if you set an fsGroup, your
containers can now see stuff in attached volumes.
Tested …

Allow cert-manager to access EKS token

---

charts/gsp-cluster/templates/00-aws-auth/managed-namespaces.yaml

Now that external-dns uses service account IAM roles, we don't need
this hack to edit the kiam permittedRolesRegex to add the
per-namespace external-dns roles

more de-kiamification of external-dns

---

charts/gsp-cluster/templates/02-gsp-system/sts-service-entry.yaml

This is necessary for apps in managed namespaces (such as
external-dns) to use the IAM roles for service accounts functionality.
Without this, the AWS SDK fails to authenticate.

Allow managed namespaces to use STS

---

modules/gsp-cluster/external-dns.tf

So that per-namespace external-dns instances can work

Allow all namespaces to assume external-dns role

---

pipelines/deployer/deployer.yaml

These aren't needed and are causing warnings in the concourse output.

remove unneeded variables from user-state

---

pipelines/deployer/main.tf

[We need minimum 2.37 so we can have ca_cert_identifier in
aws_db_instance][1].  Specifying the minimum version here will force
an upgrade if anyone (say, me) has a cached aws provider of an earlier
version.
[1]: https://github.com/terraform-providers/terraform-provider-aws/issues/10489

specify a minimum aws provider version

---

modules/gsp-cluster/data/values.yaml
modules/gsp-cluster/kiam-system.tf
modules/gsp-cluster/monitoring-system.tf
modules/gsp-cluster/values.tf

This includes a chart change from https://github.com/helm/charts/pull/18391 -
for some reason we have a fork of this chart?

Switch fluentd-cloudwatch role to use IAM roles for EKS service accounts

---

modules/gsp-cluster/data/values.yaml
modules/gsp-cluster/monitoring-system.tf
modules/gsp-cluster/values.tf

We have a log group with the same name as the cluster domain.  We no
longer write any logs to it, despite setting the fluentd-cloudwatch
`logGroupName` value to it.
This is because we override the log group name on an output-by-output
basis in the fluentd configuration file, so nothing goes to this
top-level log group.
The default value for `logGroupName` is `kubernetes` which is a log
group which doesn't exist.  Thought: maybe the default should be one
of the log groups which does exist?  In any case, it shouldn't be the
old and deprecated one.

Remove deprecated log group

---

charts/gsp-cluster/templates/00-aws-auth/gsp-default-psp-cluster-role.yaml
charts/gsp-cluster/templates/00-aws-auth/gsp-default-psp-default-role-binding.yaml
charts/gsp-cluster/templates/00-aws-auth/gsp-default-psp.yaml
charts/gsp-cluster/templates/00-aws-auth/psp-system-bindings.yaml
charts/gsp-cluster/templates/03-namespaces/namespace.yaml
pipelines/deployer/deployer.yaml

As a first pass we make use of the existing EKS-provided security policy
for the *-system namespaces, with the more restrictive policy being
deployed across all tenant namespaces.

Add pod security policies as described by ADR044.

---

modules/gsp-user/iam.tf

Currently users don't have `rds:ListTagsForResource` permission, so
they can't see tags on an RDS instace.
This grants that permission.
We checked that this won't allow users to extract the master
password.  The [AWS docs][1] say:
> Amazon RDS API actions never return the password, so this action
> provides a way to regain access to a primary instance user if the
> password is lost. This includes restoring privileges that might have
> been accidentally revoked.
[1]: https://docs.aws.amazon.com/cli/latest/reference/rds/modify-db-instance.html

allow users to see RDS tags

---

modules/gsp-cluster/service-operator.tf

we need svc-operator provisioned cloudformation stacks to be able to
update assume-role-policies and manage allow ecr:* inside the boundary

svc-operator ecr:* and iam:UpdateAssumeRolePolicy

---

components/service-operator/internal/aws/cloudformation/controller.go

the service operator should not attempt to set controller reference for
an object that is already owned by something else, this allows existing
secrets (provisioned by other means) to be the target for populating
with configuration/credentials.

stop trying to steal controller reference

---

components/concourse-operator/pkg/controller/pipeline/pipeline_controller.go

the concourse-operator currently performs set-pipeline with "check
creds" flag set ... this means that an Pipeline resource will fail to
reconcile if it uses secret variables that are not yet defined.
This behaviour is undesirable since nobody can see the reconcile error
unless they inspect the operator's logs or note the Pipeline status.
Instead, just let the operator set the pipeline, and the issues will
become visible in the concourse ui

default to NOT checking creds on pipeline apply

---

charts/gsp-cluster/templates/04-main-team-pipelines/cd-smoke-test-pipeline.yaml

We have switched to using service-operator provisioned ImageRepositories
(ECR) as the supported image storage.
Unfortunatly the docker-image resource makes some weird assumptions when
the registry uri "looks like" an ECR URI, triggering a code path that
want an AWS access key/id instead of username/password, that is
incompatible with us already knowing the username/password.
The newer builtin registry-image[1] resource does not suffer from the
same issue, but also requires us to seperate out the "build" step to
as registry-image is only responsible for pushing/pulling from
registries.
This change updates the cd-smoke-test pipeline to use the
oci-build-task[2] to build the canary, and the registry-image resource
to store the image.
[1] https://github.com/concourse/registry-image-resource …

canary: ecr based cd-smoke-test

---

charts/gsp-cluster/dashboards/concourse.json

The thing got renamed. I'm guessing this hit us at #879/#880

Fix Concourse Grafana dashboard display of container CPU metrics

---

charts/gsp-cluster/templates/04-main-team-pipelines/cd-smoke-test-pipeline.yaml

This reverts commit 26f70d69a56e0f8f993fe7c9443e93923a33b3fb.
the cache is so good that it causes builds to not trigger new deploys as
it creates canary images with identical digests.
This could probably be resolved using build-args to pass in the build
timestamp ... but just drop it (like it's hot) for now

Revert "set caches for canary build-task"

---

hack/validate-deployer-pipeline.sh
hack/validate-release-pipeline.sh
pipelines/deployer/deployer.yaml
pipelines/release/release.yaml

concourse has introduced a [set_pipeline step]( https://concourse-ci.org/set-pipeline-step.html) giving us a canonical way to perform self-updating pipelines without the need for yet another resource-type or fly-based-task.
this updates our deployer and release pipelines to use the new set_pipeline step and reduce some boilerplate yaml
also: add hack/validate-$pipeline scripts because I'm bored of remember what vars I need

use set_pipeline step in release/deploy pipelines

---

modules/gsp-cluster/data/values.yaml

We have changed how we deploy alertmanager - it's now multiple A
records on the same domain, not three different domains.
The tls_config: section is necessary because otherwise it tries to use
the IP address as the TLS ServerName and fails to validate the
certificate.

use new alertmanagers

---

modules/gsp-cluster/service-operator.tf
modules/k8s-cluster/outputs.tf

It is desirable to run scripts against provisioned databases from
concourse tasks.
We currently have seperate ci nodes from generic worker nodes (a
distinction we would like to remove at some point).
This change allows rds acesss from ci nodes.

allow rds access from ci worker nodes

---

charts/gsp-cluster/policies/digests-on-images/src.rego
charts/gsp-cluster/policies/digests-on-images/src_test.rego
charts/gsp-cluster/templates/02-gsp-system/gatekeeper/constraints/digests-on-internal-registry.yaml
modules/gsp-cluster/data/values.yaml

we currently enforce that pods can only reference images from the local
harbor registry if they use a digest. this improves our confidence that
what is running in the cluster is what we think it is, avoiding tag
mutability issues.
this adds the same restriction for images referenced from the account's
ecr registry.

enforce digest use for all images in account's ecr

---

charts/gsp-cluster/charts/gsp-monitoring/values.yaml

In 6c0c240da85edb614 we allocated 200Gb of disk for prometheus to use,
but we forgot to tell prometheus that it was allowed to use it.
This sets the retentionsize to 190Gb so we have space left for WAL and
other stuff.

let prometheus use the extra disk we gave it

---

components/service-operator/controllers/postgres_cloudformation_test.go
components/service-operator/hack/test_integration.sh

it often takes longer than a second after creation of rds resources for
the Secret and/or ServiceEntry resources to appear.
This adds longer timeouts around the tests waiting for them, and makes
the timeout variable more descriptive.
the hack/test_integration script assumed that the security group id
would be static in our sandbox test account... it isn't, so fetch it
from the api by name instead

Improve svcop test flakes

---

components/service-operator/apis/access/v1beta1/principal_types_test.go

Follows-up #931
Untested but almost certainly the cause of the latest release pipeline failure.

Fix principal tests after latest addition

---

charts/gsp-cluster/templates/02-gsp-system/service-operator/role.yaml
components/service-operator/config/rbac/role-not-patch.yaml
components/service-operator/controllers/serviceaccount.go

Do this through role-not-patch.yaml like we do for other empty string apiGroup
things.
rules[0].apiGroups: Required value: resource rules must supply at least one api
group

Fix creation of service operator role for serviceaccount access

---

README.md
docs/README.md
docs/gds-supported-platform/updating-EKS.md

**Why**
We haven't documented the process or reference doc for updating EKS.
Our GSP version badge is out of date with reality.
**What**
Create a skeleton document for the update process.
Update the GSP badge to 1.14.8

add an Update EKS doc and update GSP version badge to reflect current

---

charts/gsp-cluster/templates/03-namespaces/external-dns.yaml

A bug was introduced whereby newly-deployed external-dns instances will
fail to start up (discovered on an on-demand cluster). The problem seems
to be related to the way the RoleBinding is set up. Currently the
RoleBinding is in the wrong namespace (it's being created in gsp-system
instead of the tenant namespace). It makes sense that breaks it.
However, adding an equivalent RoleBinding to the correct namespace with
the same values otherwise doesn't fix external-dns. It has to be a
ClusterRoleBinding. Why this is is unclear to me at this stage.
Fixing it in this way doesn't break dev-namespace isolation and, as far
as I can tell, doesn't introduce any security problems. A user of a
namespace (including in-cluster concourse) cannot create cluster-wide
resources. These ClusterRoleBindings …

Fix external dns

---

charts/gsp-cluster/policies/README.md
charts/gsp-cluster/policies/isolate-tenant-istio-resources/src.rego
charts/gsp-cluster/policies/isolate-tenant-istio-resources/src_test.rego
charts/gsp-cluster/templates/00-aws-auth/auditor-cluster-role.yaml
charts/gsp-cluster/templates/02-gsp-system/gatekeeper/constraints/isolate-tenant-istio-resources.yaml
charts/gsp-cluster/templates/02-gsp-system/gatekeeper/templates/isolate-tenant-istio-resources.yaml
components/canary/chart/templates/virtual-service.yaml

Istio violates the cluster-scoped vs namespace-scoped separation with
resources such as ServiceEntry that could allow a resource created in
one namespace to affect the state of the whole cluster. This uses
gatekeeper to enforce namespace isolation for these offending istio
resource types.
Some namespaces (kube-system, gsp-system, istio-system) are excluded as
some entries need to be global (such as the egress safelist configured
in *-cluster-config).

Isolate tenant namespace istio resources

---

components/service-operator/controllers/serviceaccount.go
components/service-operator/controllers/serviceaccount_test.go

previously:
A Principal would be linked to a ServiceAccount based on ALL the
metadata.labels matching
now:
A Principal will be linked to a ServiceAccount based only on the blessed
access-group label and we ignore any ServiceAccounts that do not have
this label.
also: 
...aprently a bunch of go fmt things :woman_shrugging:

svcop: only lookup Principal based on access group label

---

components/service-operator/controllers/serviceaccount.go
components/service-operator/internal/aws/cloudformation/controller.go

the controllers can target Principals, Secrets and ServiceEntries which
may be owned by other controllers ... for Secrets we check that the
resource is not already owned before claiming ownership, this does the
same for Principals and ServiceAccounts allowing other controllers to
manage the resources without error

svcop: don't steal Principal or ServiceEntry owner

---

charts/gsp-cluster/templates/03-namespaces/namespace.yaml

We are using an ancient version of concourse-github-resource that predates the GraphQL implementation.  This either caused or made much harder to investigate a broken build yesterday.

Use modern github-resource in configure-namespace

---

charts/gsp-cluster/templates/00-aws-auth/auditor-cluster-role.yaml

There's no need for the maintenance overhead of listing individual
gatekeeper constraint resources as will always want auditors to view all
of them.

Auditors can view all gatekeeper constraint resources.

---

components/service-operator/controllers/serviceaccount.go

This was generating names such as:
`svcop-verify-verify-doc-checking-build-doc-checking-build-svcacc7q2hp`
May need to think about how we roll this out carefully.

svcop ServiceAccount controller: Add missing hyphen to generated names

---

charts/gsp-cluster/templates/03-namespaces/namespace.yaml
pipelines/deployer/deployer.yaml

We no longer wish to share this key among namespaces. Preferring instead
to have it tenant-controlled. This ensures a user in one namespace cannot
impersonate a person or agent from another namespace.
Before merging:

Remove cluster artefact signing key from tenant namespaces.

---

charts/gsp-cluster/templates/00-aws-auth/managed-namespaces.yaml
hack/lint-terraform-values-output.sh

While we're here also remove the unused ability to configure permittedRolesRegex.
(technically it's used in verify-cluster-config but set to the default value anyway - see https://github.com/alphagov/verify-cluster-config/pull/118)

svcop: Remove KIAM support for managed namespaces

---

components/service-operator/apis/access/v1beta1/principal_types.go
components/service-operator/controllers/principal_cloudformation_test.go
components/service-operator/controllers/suite_test.go
components/service-operator/internal/aws/sdk/client.go
components/service-operator/internal/aws/sdk/sdkfakes/fake_client.go
components/service-operator/internal/aws/sdk/sdkfakes/fake_client_happy.go
components/service-operator/internal/env/environment.go

This is so we can have tenants request S3 Buckets for their pipelines that can be accessed by Concourse, which can only deal with k8s Secrets and can't handle IMDS/IRSA etc. for tenants.

Copy Principals IAM credentials into their Secret

---

modules/gsp-cluster/service-operator.tf

Didn't get caught in the integration tests presumably because that will only
create fresh roles rather than try to update existing ones. Has blown up in
sandbox however.

svcop: Follow-up #965: Allow updating of roles too

---

modules/gsp-cluster/service-operator.tf

So we were still seeing things like this:
`API: iam:UpdateRole User: arn:aws:sts::011571571136:assumed-role/sandbox-service-operator/1581603874295411240 is not authorized to perform: iam:UpdateRole on resource: role svcop-sandbox-sandbox-main-testsvcacc`

Seems iam:UpdateRole doesnt have anything to do with permissions boundaries

---

components/service-operator/apis/access/v1beta1/principal_types.go
components/service-operator/controllers/suite_test.go
components/service-operator/go.mod
components/service-operator/go.sum
components/service-operator/internal/aws/sdk/client.go
components/service-operator/internal/aws/sdk/sdkfakes/fake_client.go
components/service-operator/internal/aws/sdk/sdkfakes/fake_client_happy.go
components/service-operator/internal/env/environment.go

Can't use 12h due to this constraint:
The requested DurationSeconds exceeds the 1 hour session limit for roles assumed by role chaining.

svcop: Principal credentials in Secrets: use shorter session duration

---

components/service-operator/apis/database/v1beta1/postgres_types.go
components/service-operator/apis/database/v1beta1/postgres_types_test.go
components/service-operator/apis/queue/v1beta1/sqs_types.go
components/service-operator/go.mod
components/service-operator/go.sum
components/service-operator/internal/aws/cloudformation/client.go
components/service-operator/internal/aws/cloudformation/cloudformationfakes/fake_stack.go

Do the goformation version update yak shave to get access to the new parameter. Also fix a typo and make sqs_types use our aliases.

svcop: RDS: Set CACertificateIdentifier for 2019 CA change

---

modules/k8s-cluster/data/nodegroup-v2.yaml

UPDATE_ROLLBACK_COMPLETE: ["Exactly one of [LaunchConfigurationName,InstanceId,LaunchTemplate,MixedInstancesPolicy] needs to be specified"]

Follow-up #609: Remove now-duplicate LaunchTemplate from nodegroup-v2

---

modules/k8s-cluster/data/nodegroup-v2.yaml

News apparently hasn't reached the CloudFormation team that m5ad and
r5ad instances exist.  They were only launched in March last year, we
can't expect them to be on the bleeding edge. 🙄

Work around broken CloudFormation

---

charts/gsp-cluster/charts/gsp-monitoring/values.yaml

allocate requests and limits to prometheus container 
so that we can reduce chance of it getting evicted as this will give it a qosClass of `Guaranteed`.
pods with lower Quality of Service[1] scores will be evicted first if a node
is under memory pressure[2]
in production clusters appears to desire ~7Gi based on current usage.... so setting limit at 8Gi
[1] https://kubernetes.io/docs/tasks/configure-pod-container/quality-service-pod/#create-a-pod-that-gets-assigned-a-qos-class-of-guaranteed
[2] https://kubernetes.io/docs/tasks/administer-cluster/out-of-resource/#node-oom-behavior
https://github.com/alphagov/tech-ops-cluster-config/pull/292

set resource requests/limits for prometheus

---

charts/gsp-cluster/values.yaml

By default, the cluster autoscaler won't evict a pod with local
storage - ie an EmptyDir or HostPath volume.  The reasoning is that
the pod depends on that particular node for its behaviour I guess.
This is a major problem for us because the injected istio sidecars all
have an EmptyDir volume, which means we can basically never evict any
of our pods, so we can never scale the cluster down.
I don't think it's a big deal to evict pods with HostPath or
EmptyDir.  (Most pods with HostPath will be DaemonSets anyway, so will
be unsuitable for eviction for that reason; EmptyDirs should IMO be
considered ephemeral).

Allow cluster autoscaler to evict pods with local storage

---

modules/gsp-cluster/main.tf
modules/gsp-cluster/variables.tf
modules/k8s-cluster/data/nodegroup-v2.yaml
modules/k8s-cluster/main.tf
modules/k8s-cluster/variables.tf
pipelines/deployer/deployer.tf
pipelines/deployer/deployer.yaml

Now that we use a MixedInstancesPolicy it's no longer possible to
specify a worker instance type.  So this should be removed.
Created as draft while I first remove usages from the cluster-config repos

remove unused variable worker-instance-type

---

charts/gsp-cluster/charts/gsp-monitoring/values.yaml

prometheus ran out of disk space, and got very unhappy about it. a large
number of WriteAheadLog files were required to repair/replay and the situation
got worse as prometheus continued to use up the disk. while we tell
prometheus to only retain 180Gi of metrics on disk, this limit does not
apply to the WAL files, and it seems 20Gi was not enough for it to do it's job and 
recover after a crash.
* increases disk to 500Gi
* leave retention at 180Gi (we can come back to this later)
prometheus is very memory hungry after an out-of-disk crash, prometheus
appears to need to spike memory by at least 2GB during it's WAL log
replay/recover... when combined with the initial flood of queries that
go out when prometheus gets running, this pushes it into OOMKill land
* allocate 12Gi of guarenteed …

big little prometheus 

---

modules/gsp-cluster/main.tf
modules/gsp-cluster/variables.tf
modules/k8s-cluster/main.tf
modules/k8s-cluster/variables.tf
pipelines/deployer/deployer.tf
pipelines/deployer/deployer.yaml

this adds a "generation" label to ci (concourse) worker nodes that gets
populated with a timestamp from the deployment pipeline.
becuase we would like something to cause regular rolling of ci nodes
a timer in the deployment pipeline will trigger daily, causing the
generation label to be updated in the nodegroup configuration and cause
cloudformation to roll the nodes via the same mechanism that occurs with
any other node modification.
if useful, this could easily be added to other node groups, but right
now we just want the concourse workers to get kicked at least once a
day to avoid them getting a case of bloaty-cache

add "generation" label to ci worker nodes

---

modules/gsp-cluster/main.tf
modules/gsp-cluster/variables.tf
modules/k8s-cluster/data/nodegroup.yaml
modules/k8s-cluster/main.tf
modules/k8s-cluster/variables.tf
pipelines/deployer/deployer.tf
pipelines/deployer/deployer.yaml

This adds a "NodeGroupGenerationTimestamp" cloudformation param to node
groups with a value populated with a timestamp pulled in from the
deployment pipeline.
A timer in the deployment pipeline will trigger daily, causing the
generation timestamp to be updated in the nodegroup configuration and
cause cloudformation to roll the nodes via the same mechanism that
occurs with any other node modification.
The intention is to enable periodic rolling of nodes.
The NodeGroupGenerationTimestamp does not actually _do_ anything, it
is simply interpolated into the userdata script in a harmless `echo`.
If useful, this could easily be added to other node groups, but right
now we just want the concourse workers to get kicked at least once a
day to avoid them getting a case of bloaty-cache
Note for …

add "generation" param to force node group update

---

modules/k8s-cluster/data/nodegroup-v2.yaml

Amazon support say they've fixed this and this should work now.

re-add [mr]5ad spot instance types

---

.gitattributes

To make PRs less noisy, we can mark files as generated in order to
suppress diffs on github.
This adds a single file which we definitely want to exclude.  I wasn't
100% sure about any others, feel free to add to this PR.
https://help.github.com/en/github/administering-a-repository/customizing-how-changed-files-appear-on-github

hide generated file

---

modules/gsp-cluster/main.tf
modules/gsp-cluster/variables.tf
modules/k8s-cluster/data/nodegroup-v2.yaml
modules/k8s-cluster/main.tf
modules/k8s-cluster/variables.tf
pipelines/deployer/deployer.defaults.yaml
pipelines/deployer/deployer.tf
pipelines/deployer/deployer.yaml

Currently, we set the on-demand base capacity to the same value as the
minimum-workers-per-az-count.  But in sandbox I want to set the base
capacity to 0 (so we can have 100% spot instances).
This makes the on-demand base capacity separately configurable, with a
default value of 1 (which matches the current value everywhere).
:warning: I think this will respin all the worker nodes because it
edits the launch template in the cloudformation template.

Make on-demand base capacity configurable

---

pipelines/deployer/deployer.tf

I missed one spot where we need to pass this through and so the
configuration isn't working.  This should fix it so we actually have
0% spot instances in sandbox.

Add missing plumbing for on-demand base capacity

---

docs/gds-supported-platform/gsp-service-operator.md

We renamed this and I missed a spot.
Follow-up to #1022

svcop: Fix apiVesion in docs

---

pipelines/deployer/deployer.yaml

Currently, when we drain a cluster, we leave a bunch of EBS volumes
lying around.  This is because we don't delete the persistentvolumes
correctly.  This is expensive, because each time we do this we leak
~600GB worth of EBS space (of which 500GB is prometheus).  EBS costs
$0.116 per GB-month in eu-west-2, so 600GB works out around $70/month
worth of unused EBS leaked each time we drain a cluster.
In order to do delete EBS properly, we need to delete any pod that has
a bound persistentvolume first.
Therefore, this commit:
- deletes all deployments and statefulsets (in order to delete the
pods)
- deletes all persistentvolumes and persistentvolumeclaims
This should hopefully delete the underlying EBS volumes.
I'm not sure why this is important but @chrisfarms said it
was... :shrug:

Remove more litter when deleting clusters

---

.gitattributes

You can still view it if you want but we shouldn't show it by default.

suppress the diff of go.sum in PRs

---

charts/gsp-cluster/templates/00-aws-auth/aws-vpc-cni.yaml

updates the vpc-cni to match aws eks recormendations
https://github.com/aws/amazon-vpc-cni-k8s/releases/tag/v1.5.5

upgrade vpc-cni to v1.5.5

---

pipelines/deployer/deployer.yaml

this adds a second attempt to destroy any volumes owned by the cluster
during drain by calling out to aws directly
to avoid the buildup of litter and cost
volumes _should_ be removed after PersistVolumeClaim, PersistVolume and
Pods are deleted for storage classes reclaimPolicy Delete (as we have). however we are still seeing some volumes left over are on-demand cluster destroys.
I'm not crazy about adding more to this drain script ... but I can't see a reason why this wouldn't be working already and I just want the volumes gone :woman_shrugging:

manually remove any volumes owned by cluster

---

charts/gsp-cluster/templates/00-aws-auth/auditor-cluster-role.yaml
charts/gsp-cluster/templates/00-aws-auth/operator-cluster-role.yaml

Seems our service-operator Makefile doesn't generate these files.

Add permissions for people/Concourse to interact with Redis objects

---

charts/gsp-cluster/values.yaml
modules/gsp-cluster/data/values.yaml

This removes the toleration/targeting to the special "ci" node group allowing concourse workers to run on the main node group.
It raises the min ram request to a point that will cause worker pods to likely get their own node. 
Because we don't want to maintain multiple node groups
* We want to maintain the status-quo that concourse workers get their own VM.
* This will leave a bunch of empty ci nodes doing nothing that we can then remove in a follow-up PR... but we don't do it all at once to minimise disruption.
Discuss

let concourse workers live on main node group

---

charts/gsp-cluster/templates/02-gsp-system/cloudhsm-service.yaml
charts/gsp-cluster/values.yaml
modules/gsp-cluster/data/values.yaml

At some point we accidentally deleted the `Service` that provides the
"public" ingress _and_ broke the toggle to generate the YAML (see
`alphagov/techops-cluster-config@e2b980874c27383b8891d86be7a7d88d3658eda1`).
This commit turns this back on.

Re-enable sandbox CloudHSM ingress

---

charts/gsp-cluster/templates/03-namespaces/namespace.yaml
docs/gds-supported-platform/bootstrapping-clusters.md
pipelines/deployer/deployer.defaults.yaml
pipelines/deployer/deployer.yaml

This should make it possible to:
* Run on-demand clusters without a (draft) PR open
* Try pipeline changes on sandbox branches without a (draft) PR open

Make it possible to configure deployer config and configure-namespace src resource types

---

charts/gsp-cluster/charts/gsp-monitoring/values.yaml
charts/gsp-cluster/policies/restrict-special-nodes/src.rego
charts/gsp-cluster/policies/restrict-special-nodes/src_test.rego
charts/gsp-cluster/templates/02-gsp-system/gatekeeper/constraints/tolerate-special-nodes.yaml
modules/gsp-cluster/main.tf
modules/gsp-cluster/service-operator.tf
modules/gsp-cluster/values.tf
modules/gsp-cluster/variables.tf
modules/k8s-cluster/aws-node-lifecycle-hook.tf
modules/k8s-cluster/iam.tf
modules/k8s-cluster/main.tf
modules/k8s-cluster/outputs.tf
modules/k8s-cluster/security.tf
modules/k8s-cluster/variables.tf
pipelines/deployer/deployer.tf
pipelines/deployer/deployer.yaml
pipelines/examples/clusters/sandbox.yaml

Unused since #1027. Concourse worker pods run on normal worker nodes now.

Remove the old CI nodes

---

components/aws-node-lifecycle-hook/pkg/lifecycle/handler.go
components/aws-node-lifecycle-hook/pkg/lifecycle/handler_test.go
components/aws-node-lifecycle-hook/pkg/lifecycle/heartbeat.go
modules/k8s-cluster/aws-node-lifecycle-hook.tf

we use spot instances in some clusters, but spot instances do not obey the rules of lifecycle hooks.
to ensure more graceful handling of spot termination we extend the lifecycle hook to perform the same drain functionality currently executed for ASG termination events for the spot termination warning events.
In additional to wiring up the events, we also slightly modify the drain logic to not error if node cannot be found (this is because we cannot scope the spot termination warning events to the correct asg easily, so we need to gracefully handle the case where the hook is called for a node in a different cluster - not ideal, but not so bad)

support spot termination events in lifecycle hook

---

modules/k8s-cluster/data/nodegroup-v2.yaml
modules/k8s-cluster/main.tf

We briefly had this for CI nodes from #1016, we then lost it when we merged
#1027 and #1054.

Roll worker nodes every day

---

components/service-operator/internal/aws/cloudformation/client.go

Undoes #1062. It was horribly hacky and also started failing with this error:
```
should create on Apply() [It]
/workspace/internal/aws/cloudformation/client_test.go:65
Expected
<int>: 0
to be >
<int>: 0
/workspace/internal/aws/cloudformation/client_test.go:67
```

svcop: Try checking whitelisted output key is set instead of hackery

---

modules/k8s-cluster/main.tf

Hopefully this gives us more time between having to roll the nodes in
order to deal with Concourse cruft.

Triple the EBS volume size for the cluster workers

---

components/concourse-task-toolbox/Dockerfile

Follows-up #1098
When running trivy against:
govsvc/amazon-ssm-agent@sha256:733b9eccee53fcf96bf3ab62953eda2dc5798c4f9725679b86c941a812e164ab
we were getting:
error in image scan: failed analysis: analyze error: failed to analyze layer:
sha256:17282fad1a5eb72a6f1f7a05102a1e3474fd2193cd013d44845d43c013cd594b :
failed to get packages: failed to get packages: failed to parse the pkg info: no rpm command
This seems to make it possible to run against govsvc/amazon-ssm-agent.

Add rpm to concourse-task-toolbox container

---

pipelines/deployer/deployer.yaml

The deploy might not have got as far as applying our CRDs.

Accept the CRDs not existing in the cluster on destroy

---

pipelines/deployer/deployer.yaml

Sometimes it's timed out in sandbox and it's always timing out in verify.
verify is something like 3-4x the size of sandbox in terms of number of pods.

Increase check-vulnerabilities timeout from 3m to 10m

---

charts/gsp-cluster/values.yaml

There is a poltergeist in the concourse triggering builds and
scaring the locals, we are enabling our best ghost detection system
(concourse audit logs) to try and catch it in the act.

enable all the concourse audit logs

---

charts/gsp-cluster/templates/03-namespaces/namespace.yaml
components/concourse-github-resource/assets/in

https://gds.slack.com/archives/CD1F78YJU/p1587125577073800
And various other bits and pieces that might be helpful.
Trying to figure out why this has been excluding approvals from a specific user, without being able to hijack the Little Concourse container (presumably extracting the concourse administration credentials is problematic for us to do).

concourse-github-resource: List approvers to try to debug issue

---

components/concourse-github-resource/assets/in

If you miss --raw-output when outputting a string from jq, it'll get quoted
which can break the grep below.

concourse-github-resource: Fix check for pr_author

---

components/service-operator/controllers/serviceaccount.go
components/service-operator/internal/aws/cloudformation/controller.go

increase time between reconcile retries
This will slow the time between cloudformation stack changes being
reflected in kubernetes objects by around ~15s but will result in an
order of magnitude fewer API requests.
Because we are seeing regular throttling errors from the service operator

Reduce service API throttling errors

---

components/service-operator/controllers/serviceaccount.go

there is an edge case where an error in the cloudformation status update
can mark the status as "ready" but have failed to update the info fields
that the service account controller relies on.
It's not obvious if this should be fixed in the status update code, as
the intention of that code is to reflect as much of the cloudformation
state in the resource as possible within each reconciliation loop.
It _is_ clear however that the service account annotation should always
be expected to be present, so if it is blank, then that is an error and
it should fail to reconcile
There was an incident where the role field was set to the blank state during changes to an IAM role which was not expected to be possible and we would like to avoid this.

do not update role annotation unless present

---

components/service-operator/controllers/suite_test.go

follow up from https://github.com/alphagov/gsp/pull/1123 to fix unit
tests with the fake client

fix missing fake output for svcop unit tests

---

charts/gsp-cluster/values.yaml
components/concourse-task-toolbox/bin/findCVEs.py

Compare:
trivy --ignore-unfixed -s CRITICAL fluent/fluentd-kubernetes-daemonset:v1.7.3-debian-cloudwatch-1.0
with:
trivy --ignore-unfixed -s CRITICAL fluent/fluentd-kubernetes-daemonset:v1.9.3-debian-cloudwatch-1.0
Difference appears to be:
```
+----------------+------------------+----------+-------------------+---------------+---------------------------------------------+
|    LIBRARY     | VULNERABILITY ID | SEVERITY | INSTALLED VERSION | FIXED VERSION |                    TITLE                    |
+----------------+------------------+----------+-------------------+---------------+---------------------------------------------+
| linux-libc-dev | CVE-2019-10220   | CRITICAL | 4.9.189-3+deb9u1  | 4.9.210-1     | kernel: CIFS: Relative paths                |
|                | …
```

Upgrade fluentd-cloudwatch from v1.7.3 to v1.9.3 to avoid some trivy critical warnings

---

components/concourse-task-toolbox/bin/findCVEs.py

Instead only whitelist specific images that fail.
This introduces checking on the following things currently running in sandbox:
quay.io/coreos/kube-state-metrics:v1.9.4
quay.io/jetstack/cert-manager-cainjector:v0.11.0
quay.io/jetstack/cert-manager-controller:v0.11.0
quay.io/jetstack/cert-manager-webhook:v0.11.0

check-vulnerabilities: Stop whitelisting quay.io

---

components/canary/chart/templates/prometheus-rules.yaml

we are ignoring the flakes of the canary rotation alert at the moment as
it recovers quickly within 10m, this means we are not paying attension
when something is really wrong.
this reduces the setitivity of the alert so that a single failure should
not fire the alert .

only fire canary alert if consistant for 15mins

---

components/concourse-task-toolbox/Dockerfile
components/concourse-task-toolbox/bin/findCVEs.py
pipelines/deployer/deployer.yaml

This is to work around trivy being unwilling to work with their seemingly
broken responses, see https://github.com/aquasecurity/trivy/issues/401#issuecomment-611454832
This begins vulnerability checking on the following containers:
quay.io/bitnami/sealed-secrets-controller:v0.7.0
quay.io/calico/node:v3.8.1
quay.io/open-policy-agent/gatekeeper:v3.0.4-beta.1
quay.io/kiali/kiali:v1.9
This involves making the container privileged and running dockerd. This sounds scary so someone should check all the implications of this.

check-vulnerabilities: Stop whitelisting some images that just need pulling down first

---

pipelines/deployer/deployer.defaults.yaml

Following on from EKS control plane upgrade to 1.15

bump EKS worker nodes to 1.15

---

docs/gds-supported-platform/updating-EKS.md

The existing document provides an example of updating via AWS AMI versioning. We no longer do this but update the worker EKS version inline with the EKS control plane version.
Update the example to reference the current method of updating worker nodes EKS version.

Update the Updating EKS doc

---

modules/k8s-cluster/main.tf

We have seen issues where, during a terraform apply, not all the nodes
will roll. This appeared to be tied to availability zone - all nodes in
an AZ worker group would roll but none of the others would. We're
working on the hypothesis that the trigger is the change in the
"desired" count that is caused by the cluster autoscaler. By ignoring
this value we hope to avoid unnecessary node rolls.

Ignore changes to current running worker counts

---

charts/gsp-cluster/charts/gsp-monitoring/values.yaml

A short-term "fix" while we wait for the upstream charts to upgrade.

Upgrade grafana.

---

pipelines/deployer/deployer.yaml
pipelines/release/release.yaml

The concourse upgrade to 6.3 has broken the GSP pipelines. Time to move off deprecated things...

Use set_pipeline step instead of concourse-pipeline resource

---

pipelines/deployer/deployer.yaml

I think we've hit a concourse bug when we upgraded from concourse
6.0.0 to 6.3.0.  I've filed concourse/concourse#5799 upstream to
capture this.  In the meantime, I think we can work around this by
forcing each task to use a different volume.
This fix works by avoiding reusing the same volume; instead, we create
new volumes at each step and copy the files from the old into the new.
Some details to note:
- the old `platform` volume was somewhat abused - it was both the
assets from the github release and the untarred source code from
the git repo.  this commit splits those up into a
`platform-release` volume and a `platform-source` volume.
- in the `deploy` job, we modify the source multiple times, so
we also need volumes called `platform-source-with-hook` and
`platform-merged-source`
- …

work around concourse volume problem in deployer pipeline

---

components/concourse-task-toolbox/bin/findCVEs.py

The check-vulnerabilities step is broken with the output:
```
Command '['trivy', '--format', 'json', '--quiet', '--ignore-unfixed', '-s', 'CRITICAL', 'quay.io/calico/typha:v3.13.0']' returned non-zero exit status 1.
```
It looks like we tried to safelist this artefact but didn't update the
version when we upgraded calico.
More generally, it would be good if the check-vulnerabilities pipeline
step actually output the problem that it encountered, rather than just
exit status 1.

fix check-vulnerabilities

---

components/concourse-github-resource/assets/in

`comm` relies on the input lists being sorted.
GNU coreutils and BusyBox it turns out have different behaviour for `sort -d`.
I believe this was causing certain combinations of approvers to be treated as
invalid.

concourse-github-resource: Ignore case when sorting lists of approvers

---

pipelines/deployer/deployer.yaml

In order to roll out an upgrade to the prometheus operator we need to
delete some jobs created by the previous upgrade. "helm install" would
normally handle this for us but as we don't use "helm install" we need to
tackle this ourselves.

Delete immutable objects from previous prometheus installation

---

charts/gsp-cluster/dashboards/concourse.json

During some recent incidents it would have been useful to see what state
the nodes that were running the concourse worker pods were in. This adds
a couple of panels that may be useful.
"Worker node CPU" and "Worker node memory" are the new panels.

Add panels relating to nodes to concourse grafana dashboard

---

charts/gsp-cluster/values.yaml

This is a hack to attempt to encourage the kube scheduler to put the
concourse worker pods onto otherwise quieter nodes.

Attempt to improve concourse worker performance

---

charts/gsp-cluster/charts/gsp-monitoring/values.yaml

To aid with tracking and diagnosing a concourse issue relating to the
allocation of memory it would be easier to be able to see into the kernel's
memory fragmentation over time.

Add "buddyinfo" collector for the prometheus node exporter

---

components/concourse-github-resource/assets/in

May sometimes be useful (like today) to debug strange behaviour from GitHub.
Should not contain any sensitive information AFAIK.

concourse-github-resource: Log API response

---

components/concourse-task-toolbox/Dockerfile

update base image to pull in newer versions of `git` and `libssh2`

task-toolbox: bump base image

---

components/concourse-task-toolbox/Dockerfile

update task-toolbox so that it leaves `pip` in the image.
purging python pip appears to remove a whole bunch of deps required by other
libraries/scripts so it does not seem sensible to remove it.
This was causing the `aws` cli to fail to execute complaining about missing deps.

task-toolbox: don't purge pip from image

---

charts/gsp-cluster/templates/02-gsp-system/sealed-secrets-controller.yaml

To prepare for EKS 1.16 support.

sealed secrets controller: Use apps/v1 instead of apps/v1beta1

---

charts/gsp-cluster/charts/gsp-monitoring/values.yaml
pipelines/deployer/deployer.yaml

The kube-apiserver is part of the EKS control plane, so, from a metrics
and alerting point of view we aren't interested. So remove the associated
rules.

Remove unwanted prometheus rules

---

charts/gsp-cluster/templates/04-main-team-pipelines/cd-smoke-test-pipeline.yaml

we are seeing the "build" job run more often than the "deploy" job in
the smoke test pipeline.
Sometimes the "deploy" job waits around for some time (~10mins) before triggering,
resulting in the CanaryOverdue alert firing.
It's not 100% clear why this is happening, and an investigation could be
yak shavey at this point, but as a quick experiement this changes the
job to be triggered on the timer resource rather than the ecr repository
in case the issue is with the check loop of the ecr resource and
increases the interval a little in case the issue is with some kind of
locking while the deploy job is "putting" to the ECR resource (total
guess work).

canary: trigger deploy from timer

---

charts/gsp-cluster/templates/04-main-team-pipelines/cd-smoke-test-pipeline.yaml

we are still seeing the canary's "deploy" job stall.
try triggering on "every" ECR image built, rather than the latest.

canary: trigger on every version

---

charts/gsp-cluster/values.yaml

we see issues in long lived pipelines with large numbers of build logs
retained ... this defaults retained logs to 500 (which can be manually
overriden in pipelines) and caps a max at 5000

concourse: limit retained builds to 500 - 5000

---

components/concourse-task-toolbox/bin/findCVEs.py

check-vuln is always red because there are tenant pods referencing the
old harbor registry ... let's just ignore it

check-vuln: ignore old images

---

charts/gsp-cluster/templates/00-aws-auth/aws-vpc-cni.yaml
charts/gsp-cluster/templates/00-aws-auth/kube-proxy.yaml
charts/gsp-cluster/templates/02-gsp-system/calico.yaml

https://docs.aws.amazon.com/eks/latest/userguide/update-cluster.html recommends:
* AWS VPC CNI 1.6.3 (note they've also updated the 1.15 recommendation to this
as well)
* CoreDNS 1.6.6 (which we have)
* KubeProxy 1.16.12
Don't do this until after https://github.com/alphagov/gsp/pull/1171

Update AWS VPC CNI and KubeProxy for EKS 1.16

---

charts/gsp-cluster/policies/restrict-special-nodes/src_test.rego
charts/gsp-cluster/templates/02-gsp-system/gatekeeper/constraints/tolerate-special-nodes.yaml
charts/gsp-cluster/templates/02-gsp-system/gatekeeper/gatekeeper.yaml
charts/gsp-cluster/values.yaml
modules/k8s-cluster/main.tf
pipelines/deployer/deployer.yaml

https://v1-16.docs.kubernetes.io/docs/setup/release/notes/
`removed the ability to set kubernetes.io- or k8s.io-prefixed labels via --node-labels, other than the specifically allowed labels/prefixes. (#79305, @paivagustavo)`
https://github.com/kubernetes/enhancements/blob/master/keps/sig-auth/0000-20170814-bounding-self-labeling-kubelets.md#proposal

Try to fix creating nodes with worker-eks-version=1.16

---

pipelines/deployer/deployer.yaml

This was added in https://github.com/alphagov/gsp/pull/1173
A release with this code was promoted so we should be fine.
This code has been breaking cluster bootstrap because it runs before applying
the other resources but refers to non-core stuff like ServiceMonitor.

Remove temporary tidyup code

---

components/service-operator/Makefile
components/service-operator/apis/database/v1beta1/postgres_types.go
components/service-operator/apis/database/v1beta1/postgres_types_test.go

Without setting the version RDS defaults to "latest", which isn't in line
with our parameter group family, which does lock in the version. So,
explicitly lock the engine version to keep it consistent with the parameter
group.
An alternative would be to expose some sort of parameter through the yaml
and align accordingly, but given the EOL mode of GSP this is the simplest
change that will work.

Lock the engine version of RDS aurora-postgres

---

components/service-operator/apis/database/v1beta1/postgres_types.go

This will prevent the controller and CloudFormation from trying to replace
existing instances.

Keep the RDS version consistent with existing RDS instances

---

components/service-operator/apis/database/v1beta1/postgres_types.go
components/service-operator/apis/database/v1beta1/postgres_types_test.go

The instances seem to "update" fine, but the "cluster" update keeps failing
so revert the change to the cluster.

Remove engine version from RDS cluster

---

charts/gsp-cluster/templates/02-gsp-system/service-operator/crd/database.govsvc.uk_postgres.yaml
components/service-operator/apis/database/v1beta1/postgres_types.go
components/service-operator/apis/database/v1beta1/postgres_types_test.go

The change in "default" AWS aurora postgresql versions is causing
nightmares. So allow a version to be specified in the resource yaml and
ensure the parameter group family is updated accordingly.
bit more context:
This is the continued work from: https://github.com/alphagov/gsp/pull/1183 which is attempting to solve the issues causes by the service-operator not specifying the exact version (resulting in each instance being provisioned with the version that is latest at time of creation).
To make things worse, specifying an EngineVersion in the cloudformation (where previously it was using the default value) still counts as a "change" and requires recreating the instances ... so this is a workaround to avoid that edge case and allow all the existing DBs to stay as they are

Allow engine version to be specified and align parameter group family

---

components/aws-ssm-agent/Dockerfile
components/concourse-operator/README.md

Add fresh signatures for top commits in aws-ssm-agent and concourse-operator components by making arbitrary formatting fixes.
Because daniel rotated his signing key in github and so the API doesn't consider his signatures valid any more.

arbitrary formatting fixes to re-sign some commits

---

charts/gsp-cluster/templates/04-main-team-pipelines/cd-smoke-test-pipeline.yaml

https://trello.com/c/UPQiRxS1
Concourse has an odd quirk that will result in the deploy job occasionally getting delayed by up to half an hour, which causes the canary check to fail. This only seems to happen if we're expecting to be triggered by the finish of a previous job, so just merge these jobs to stop this happening.
Thanks to all for showing me the way here.

cd-smoke-test pipeline: merge build & deploy jobs

---

charts/gsp-cluster/charts/gsp-monitoring/dashboards/concourse-internal.json
charts/gsp-cluster/charts/gsp-monitoring/templates/concourse-internal-dashboard.yaml

Fell out of https://trello.com/c/UPQiRxS1
This exposes some more concourse-specific metrics as opposed to the resource-focused metrics of the existing dashboard. Could potentially bring it to big concourse at some point too.

grafana: add "concourse internal" dashboard

---

charts/gsp-cluster/values.yaml

We can't bump the chart to 14.x as that requires Helm v3.

Bump Concourse chart to app version 6.6.0

---

components/concourse-operator/Gopkg.lock
components/concourse-operator/pkg/apis/concourse/v1beta1/pipeline_types.go
components/concourse-operator/pkg/controller/pipeline/pipeline_controller.go
components/concourse-operator/pkg/controller/pipeline/pipeline_controller_test.go
components/concourse-operator/pkg/webhook/default_server/pipeline/validating/pipeline_create_update_handler.go
components/concourse-operator/pkg/webhook/default_server/pipeline/validating/pipeline_create_update_handler_test.go

Recent changes in the concourse atc.Config type have caused an
incompatibility between how the k8s apimachinry wants to unmashal the
resource spec into the type and how concourse expects atc.Config to be
unmarshaled.
Essentially previously a simple json.Unmarshal would have populated an
atc.Config correctly, whereas now the dedicated atc.UnmarshalConfig is
the only way to get a reliable decode.
To solve this, I have wrapped the Pipeline.Spec.Config in a type of our
own that implements the json.Unmarshaler interface to catch the decoding
and populate the Config as expected ... this is a bit ugly, but it was
simpler than attempting to catch the decode on the Spec and have to pick
the fields apart.
I may raise a PR upstream to implement Unmarshaler on atc.Config
directly as this seems like …

concourse-op: fix unmarshaling of atc.Config from Pipeline resources

---

modules/k8s-cluster/main.tf

Like is done for the worker nodes, to facilitate having them replaced
with new machines by updating the timestamp.

Use a timestamp for the kiam server nodes

---

charts/gsp-cluster/charts/fluentd-cloudwatch/templates/daemonset.yaml
charts/gsp-cluster/templates/00-aws-auth/gsp-system-namespace.yaml
charts/gsp-cluster/templates/00-aws-auth/istio-namespace.yaml
charts/gsp-cluster/templates/00-aws-auth/kube-system-namespace.yaml
charts/gsp-cluster/templates/01-aws-system/aws-ssm-agent-daemonset.yaml
charts/gsp-cluster/templates/02-gsp-system/pipeline-operator.yaml
charts/gsp-cluster/templates/02-gsp-system/service-operator/deployment.yaml
charts/gsp-cluster/templates/03-namespaces/external-dns.yaml
charts/gsp-cluster/templates/03-namespaces/namespace.yaml
charts/gsp-cluster/templates/04-main-team-pipelines/cd-smoke-test-pipeline.yaml
charts/gsp-cluster/values.yaml
charts/gsp-istio/values.yaml
hack/lint-terraform-values-output.sh
modules/gsp-cluster/data/values.yaml
modules/gsp-cluster/values.tf
modules/gsp-cluster/variables.tf
pipelines/deployer/deployer.tf
pipelines/deployer/deployer.yaml

To avoid rate limiting problems.
These will be different credentials to those used in the release pipeline -
these will be shared with tenants and therefore will not be given any special
push permissions, they will be used for pulling things like Istio containers,
and other public images from DockerHub.
Provide it in the Docker config format for Kubernetes, and a secret with
username and password for use in Concourse.

Provide DockerHub credentials to tenants and various system components

---

charts/gsp-cluster/templates/04-main-team-pipelines/cd-smoke-test-pipeline.yaml

So we don't get caught in rate limiting issues when trying to pull a FROM image
Based on this hack courtesy of Andy Paine: https://github.com/vito/oci-build-task/issues/14#issuecomment-596731775

Authenticate to DockerHub when building canary image

---

components/canary/Dockerfile

Build breaks with golang 1.16, probably not worth fixing at this late stage in GSP's lifetime.

canary: pin Dockerfile to known working base image versions
